### ISSUE TITLE
Write RecordingExtractor to read and extract metadata from Bonsai files

### ISSUE THREAD

**Issue by nicolocin** [catalystneuro/neuroconv#10]
Write BonsaiRecordingExtractor using template provided [here](https://spikeinterface.readthedocs.io/en/latest/recording_extractor.html).  Sample extractors for other formats can be found [here](https://github.com/SpikeInterface/spikeextractors/tree/master/spikeextractors/extractors).

Some ideas of what methods to include:
- Extract:
  - sampling rate
  - starting time
  - channel IDs
  - number of frames
- Units conversion

@bendichter @glopesdev - anything else?

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Reference to previous code DANDI team put together for this: https://github.com/dandi/neuroconv/blob/master/src/neuroconv/BonsaiRecordingExtractor.py

What we could really use here to make this happen is some example data

**Comment by CodyCBakerPhD** [comment]
@glopesdev Hi there, at long last I'm getting around to implementing this - do you happen to have any example raw ephys files saved through a Bonsai workflow (together with the `.bonsai` header file)?

Ditto for detected/sorted spiking data that's been saved to the file format through Bonsai (or is this identical to OpenEphys `.spikes` files?)

**Comment by CodyCBakerPhD** [comment]
Replaced by #47
