### ISSUE TITLE
[Documentation] Do not display private methods in the API

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#1009]
Currently we are showing this:

https://neuroconv.readthedocs.io/en/main/api/tools.spikeinterface.html#neuroconv.tools.spikeinterface.spikeinterface._recording_traces_to_hdmf_iterator

![image](https://github.com/user-attachments/assets/1f4eec70-4ea6-465d-b360-756d3482c8ca)

I think it would be better if we did not.

**Comment by CodyCBakerPhD** [comment]
I also wish it formatted like `black` does

**Comment by h-mayorquin** [comment]
You mean like?
```
function(
arg1,
arg2,
arg3,
)

```

Yeah, that would look better.
