### ISSUE TITLE
[Feature]: Add arm64 Mac testing

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#1054]
### What would you like to see added to NeuroConv?

Just noticed that the testing matrix does not include `macos-latest` which uses arm64 (not intel) runners: https://github.com/catalystneuro/neuroconv/blob/main/.github/workflows/testing.yml#L23

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
I did not do this in spikeinterface because maxwell is failing but I had the vague memory that we don't really test for maxwell here.
