### ISSUE TITLE
[Feature]: Anatomical annotation of units in spike sorting?

### ISSUE THREAD

**Issue by vigji** [catalystneuro/neuroconv#1064]
### What would you like to see added to NeuroConv?

I am sorry if I missed this feature. I am using the `KiloSortSortingInterface` to load some units sorted using KS4 via `spikeinterface`. 

For each unit, I also have a pipeline that produces the brain area where the unit is located. I am wondering what is the way you would recommend to include that information in the sorting data. Is this something advisable? What would be a `neuroconv`-itonic way of doing it?

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
Hi, the most straightforward way would be to do the following
```python
from neuroconv.tools.testing import MockSortingInterface

# Here use your KiloSortSortingInterface instead
interface = MockSortingInterface()
key = "brain_area"
interface.sorting_extractor.set_property(key=key, values=["Hippocampus", "CA1", "Motor Cortex", "Another Location"])


nwbfile_path = "test.nwb"
interface.run_conversion(nwbfile_path=nwbfile_path, overwrite=True)

from pynwb import NWBHDF5IO
with NWBHDF5IO(nwbfile_path, 'r') as io:
    nwbfile = io.read()
    units_table_df = nwbfile.units.to_dataframe()
units_table_df
```

![image](https://github.com/user-attachments/assets/ce0238e3-5d3e-496d-b747-f23e0879f7e6)


 Are you also writing a raw ecephys data? If so, the "best" way would be to annotate the channels/electrodes in the electrodes table and then make a reference from the units table there.

**Comment by vigji** [comment]
Well that was another question I was about to ask :)

Am I correct in thinking that by looking at the RecordingEstractorImage there is no way to link the bulk of the raw data as I do for the video recordings?

I would like to bundle everything together in a single nwb file, but I was wondering if I could keep those ~100 GBs out of it, as lab policy is still not deleting OEphys source data even after succesfull nwb import.

**Comment by h-mayorquin** [comment]
> Am I correct in thinking that by looking at the RecordingEstractorImage there is no way to link the bulk of the raw data as I do for the video recordings?

No, unless your original data is in hdf5 but that is not dandi friendly and introduces more complexity in your workflow as you need to be sure to keep the paths aligned:

https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/plot_linking_data.html

Did the annotation method above worked for you?
Let me know so I can close this question. Feel free to open more for any question you might have.

**Comment by vigji** [comment]
YEs it does! thank you very much :) And thanks for the clarification!
