### ISSUE TITLE
[Feature]: Add support for .csv output files from DeepLabCut

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/neuroconv#1131]
### What would you like to see added to NeuroConv?

DeepLabCut optionally exports to .csv instead of .h5 (https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html), so DeepLabCutInterface should be able to support both types of outputs.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by pauladkisson** [comment]
Yes, the Jadhav Lab data has .csv DlC data.  That's how I found out about this issue.

**Comment by h-mayorquin** [comment]
Are they using only the csv or do they have both csv and h5?

I was asking if we can use our data in our testing suite / gin / s3.

**Comment by pauladkisson** [comment]
> Are they using only the csv or do they have both csv and h5?

Only .csv

Jacob has been cooperative with data sharing with Spikegadgets so we will likely be able to add their data to our gin as well.
