### ISSUE TITLE
What's the best way to establish conversion for a custom "convention" storing data in .mat files in Matlab

### ISSUE THREAD

**Issue by yarikoptic** [catalystneuro/neuroconv#1134]
The convention described at https://mvdmlab.host.dartmouth.edu/wiki2/doku.php?id=analysis:nsb2017:week2#introduction_to_neural_data_types . Primarily it is already spike sorted data (spike timings), LFP (continuous), events into .nwb files.  Should we code directly in pynwb? or matnwb?  or there is some help from neuroconv abstactions to somehow just "route" data sources and convert some metadata types readily?

Thank you for the guidance.

**Comment by h-mayorquin** [comment]
Hi,

In my opinion, Neuroconv doesn't offer an easy abstraction that would help you speed up your process. Let me explain.

Neuroconv works well for building interfaces that automatically extract data from common and stable formats. If the format or convention in MATLAB is stable and widely used, it makes sense to build an interface in Neuroconv so other users can benefit. A good example is the CellExplorer format by György Buzsáki, MD, PhD, which I describe in more detail below. However, this is not commonly the case in my experience. MATLAB conventions tend to be neither popular nor stable enough to justify the effort of writing an interface. In most of our conversions that involve interacting with MATLAB code, we write conversion-specific code to achieve this. [Here's a recent example.](https://github.com/catalystneuro/cohen-u01-to-nwb/blob/main/src/fox_lab_to_nwb/behavior.py)

Regarding the choice between Python and MATLAB, I think it largely depends on who is doing the conversion. If the person is more proficient in MATLAB, then it might be a good choice to write the conversion code in MATLAB. Neuroconv is a Python library, and most of us have expertise in Python, so we do our conversions in Python. Another consideration is that Python support is generally better, so if all else is equal, I would opt for Python.

Those are the trade-offs I would consider.

To shed further light on what the effort with Neuroconv would look like, I can describe how the code to extract spike timings for the CellExplorer Buzsáki lab format works.

The Neuroconv way of doing this would be to create an interface to extract the data. You can see a good example in the CellExplorerInterface:

A sorting extractor in SpikeInterface reads the data from the MATLAB convention as a sorting extractor object.
The interface in Neuroconv uses the sorting object from SpikeInterface and also reads the metadata from the MATLAB code. They work together for extracting the data to NWB, and Neuroconv does have facilities to route the data to the correct types into NWB.

[CellExplorerInterface code](https://github.com/catalystneuro/neuroconv/blob/cbf68d4c6d7a3a5c942586e228a90063fe161b22/src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py#L415-L595)

[SpikeInterface code](https://github.com/SpikeInterface/spikeinterface/blob/e525d85948009e7dc57579a8a428502a5534c111/src/spikeinterface/extractors/cellexplorersortingextractor.py#L10-L39)

But you would need to build objects like this.

I hope this was useful in giving you a better idea of the effort involved in building an interface versus using custom code. Feel free to ask any more questions or reach out to me on Slack for a short discussion if you need

**Comment by yarikoptic** [comment]
Thank you @h-mayorquin ! attn @manimoh @mvdm :point_up:
