### ISSUE TITLE
[Bug]: No ImportError when calling `from neuroconv.utils import NWBMetaDataEncoder`

### ISSUE THREAD

**Issue by rly** [catalystneuro/neuroconv#1141]
### What happened?

In https://github.com/catalystneuro/neuroconv/pull/1050, some classes such as `NWBMetaDataEncoder` were renamed `_NWBMetaDataEncoder`. This breaks code in NWB GUIDE that calls `from neuroconv.utils import NWBMetaDataEncoder`. Because of the override to `__getitem__` in `neuroconv/utils/__init__.py` (https://github.com/catalystneuro/neuroconv/pull/1033), the line `from neuroconv.utils import NWBMetaDataEncoder` now fails silently. It should return something like `ImportError: cannot import name 'AA' from 'collections' (/Users/rly/mambaforge/envs/test/lib/python3.12/collections/__init__.py)` but `NWBMetaDataEncoder` is set to None without an error. This was confusing to debug.

I suggest changing `__getitem__` to end with something like:
```python
if name in globals():
    return globals()[name]
raise ImportError(f"cannot import name '{name}' from 'neuroconv.utils'")
```
ref: https://peps.python.org/pep-0562/

I am also in favor of making `NWBMetaDataEncoder` public again since it is used by NWB GUIDE. But if not, I can just copy the code over to NeuroConv...

### Steps to Reproduce

```python
from neuroconv.utils import serjsklfjskl
```

### Operating System

macOS

### Python Executable

Python

### Python Version

3.12

### Package Versions

neuroconv==0.6.5

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
Let's make it public again. This was an oversight by both Cody and I when we were trying to clean the API docs. 


Concerning the silent error with import, damn, they always warn about you about hacking dunders and side effects...
