### ISSUE TITLE
reading TDT

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#13]
Can we support reading TDT data? It looks like this is not yet supported by SpikeInterface, but is supported by python-neo.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/extractors/neoextractors/tdt.py

It is supported in the new spikeinterface API!

**Comment by CodyCBakerPhD** [comment]
Great, just need the Interface for it, then!
