### ISSUE TITLE
Centralize definitions for metadata schemas

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#14]
Adding this to the global to-do list, low priority. Would be another good first issue to tackle for someone learning the metadata details. 

**Describe the solution you'd like**
Some of the base interfaces, such as the [RecordingInterface](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py#L50-L63), explicitly set definitions for their metadata schema structures.

These could and probably should be centralized into a single util location, and can also probably be generalized due to similarities across interfaces.

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you checked our [Contributing](https://nwb-conversion-tools.readthedocs.io/en/master/developer_guide.html) document?

**Comment by h-mayorquin** [comment]
Linking here from #113 so this discussion is not lost. I agree with @CodyCBakerPhD that this is desirable as our metadata and the one in the API that is generated on the fly do not match. I would rather prefer to have ours hard-coded so we can consult it in an easier way (plus we have less code to maintain).  There must be another way of assuring ourselves that we are up to date but I am not that concerned about this as the schema does not -should not?- change this fast.

I add the link here to Cody's specific comment so it does not get lost once we merge the other issue:
https://github.com/catalystneuro/neuroconv/pull/113#issuecomment-1227724347

How are you thinking about this, @bendichter ?

**Comment by h-mayorquin** [comment]
Another advantage of having the schema right now is that we can point it to users to it in the documentation (ideally, we should be able to point them to the real schema but as we mentioned, it is not identical).

**Comment by CodyCBakerPhD** [comment]
Was closed accidentally by the first of several PRs necessary to finish this across the metadata structure
