### ISSUE TITLE
DataInterface for Neuralynx spike sorting formats

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#16]
### What would you like to see added to nwb-conversion-tools?

…

### What solution would you like?

…

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by h-mayorquin** [comment]
Pushed a PR for spikeinterface here:
https://github.com/SpikeInterface/spikeinterface/pull/854
