### ISSUE TITLE
Neuralynx metadata improvements

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#185]
During the discussion of #170 some things were left to-do. I am writing them here to keep track.

- [x] Add capability to `add_electrodes` to write collumns with boolean values (and remove the code from this on neuralynx)
- [x] Check whether `NeuralynxRecordingInterface`,  initialization or writing process fails when non `ncs` files are present in the `folder_path`.

**Comment by JuliaSprenger** [comment]
Hi @h-mayorquin To clarify this: By the 2nd point you to test what happens if a session contains **only** non-`ncs` files, so no continuous data, right?

**Comment by h-mayorquin** [comment]
Yes, I corrected the issue to reflect this. Hopefully it is more clear now.

**Comment by CodyCBakerPhD** [comment]
> Add capability to add_electrodes to write collumns with boolean values (and remove the code from this on neuralynx)

To be clear, we cannot currently write a recording object with channel properties that are set to boolean values? (and not missing any data for any channels). I just wonder how this would work with append mode, like when you write one recording object that doesn't have that column defined, then write a second one that does define it - what value is used to auto-populate the rows of the previous recording in that case? Seems like we'd actually want a 3-state variable (`False, True, NaN`) but at that point perhaps it would be better to upcast it to float so we don't have to define our own standard for what a `NaN` value is in this case...

**Comment by h-mayorquin** [comment]
> > Add capability to add_electrodes to write collumns with boolean values (and remove the code from this on neuralynx)
> 
> To be clear, we cannot currently write a recording object with channel properties that are set to boolean values? (and not missing any data for any channels). I just wonder how this would work with append mode, like when you write one recording object that doesn't have that column defined, then write a second one that does define it - what value is used to auto-populate the rows of the previous recording in that case? Seems like we'd actually want a 3-state variable (`False, True, NaN`) but at that point perhaps it would be better to upcast it to float so we don't have to define our own standard for what a `NaN` value is in this case...

Yes, we can't not, because we are missing default values. Good point about the nan issue.

**Comment by CodyCBakerPhD** [comment]
Cleaning up some old issues

Item 1 was resolved in #217, item 2 seems the responsibility of neo/SI so I'll leave it up to @JuliaSprenger who would probably know best what would happen in that case

**Comment by h-mayorquin** [comment]
The last point was about the folllowing:
If there are non `ncs` files in a folder should the interface fail explitly or silently. Context, you are running a conversion with a lot of sessions that contain data but some of them don't have the necessary data to instantiate the recording (the `ncs` files) (see [here](https://github.com/catalystneuro/neuroconv/pull/170#discussion_r998132009) for the discussion).  Therefore, it is a local responsability and not a neo thing,

I remember discussing this with you and we both think that the interface should fail excplitily (throw an assertion if the files are not found). In other words, logic for missing data should be handled at the conversion script level and not at the interface level. This is probably the way that is working right now but I don't remember testing this.
