### ISSUE TITLE
Adding new numpy typing conflicts with `get_source_schema`

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#20]
Recently numpy has introduced new typing for array and dtypes:

https://numpy.org/devdocs/reference/typing.html

However, our machinery for calculating the source schema finds some bugs because of (at least right now) two reasons:
1 ) They are made of the Union (in the typing sense) of many types and some of those do not have an attribute name which we use in our `get_schema_from_method_signature` function:

https://github.com/catalystneuro/nwb-conversion-tools/blob/16126dbd3039444a3c74fa8a371cc43a596b07e5/src/nwb_conversion_tools/utils/json_schema.py#L76

2) Sometimes there are multiple hits with respect to our types to json maping and the following lines fail.
https://github.com/catalystneuro/nwb-conversion-tools/blob/16126dbd3039444a3c74fa8a371cc43a596b07e5/src/nwb_conversion_tools/utils/json_schema.py#L81

I opened PR catalystneuro/nwb-conversion-tools#544 to showcase this issue.

**Comment by CodyCBakerPhD** [comment]
Wow, this issue is so old it refuses to be linked to the active PR to solve it

@h-mayorquin WDYT, can we close this now with https://github.com/catalystneuro/neuroconv/pull/1016?

**Comment by h-mayorquin** [comment]
Let's close it x D
