### ISSUE TITLE
[Feature]: Support Plexon data types

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#204]
### What would you like to see added to NeuroConv?

We should add support for Plexon data types. Plexon writes data to .plx and .pl2 and offline sorters write data to .ddt and .nex.

* It looks like we already have data in the GIN repo the legacy .plx format and there's already support in neo and SpikeInterface for reading it, so it shouldn't take too much to create a new reader for .plx data
* For the other data types, let's start the process of tracking down test data and adding them to the GIN repo

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by khussein7** [comment]
Hi! Has there been development into converting .pl2 files into nwb without dependencies from Plexon's Python SDK (e.g., dll files), especially for Apple Silicon users? Thanks in advance for your help.

**Comment by CodyCBakerPhD** [comment]
@khussein7 Last known work was from https://github.com/NeuralEnsemble/python-neo/issues/1124 leading to https://github.com/NeuralEnsemble/python-neo/pull/1214 which has not been released officially yet but could be used from a dev branch

If there are issues specific to Apple Silicon using our PlexonInterface here on NeuroConv applied to a `.pl2` file, with that dev mode of neo master branch installed in the environment, I'd say chime in on the original issue https://github.com/NeuralEnsemble/python-neo/issues/1124 to see if that's even something that could be supported given the technological nature of the DLL reader over there

**Comment by bendichter** [comment]
I'm going to reopen this for the pl2 datatype, which was just requested during the Conversion Workshop

**Comment by CodyCBakerPhD** [comment]
Looks like we just need to route to the other recording extractor for pl2: https://github.com/SpikeInterface/spikeinterface/blob/17ee78552ddff147e1aaefcac70364c4a8520d99/src/spikeinterface/extractors/tests/test_neoextractors.py#L356

**Comment by bendichter** [comment]
@h-mayorquin , can you look into this?

**Comment by h-mayorquin** [comment]
I took a first stab at this. There are some error in windows that I found here:
https://github.com/SpikeInterface/spikeinterface/pull/2937

I will sit on my windows machine and work on this later this week.

**Comment by bendichter** [comment]
@h-mayorquin we have another request for pl2. Would it be possible to build a data interface for this? What are the issues with Windows?

**Comment by h-mayorquin** [comment]
Some errors:
https://github.com/NeuralEnsemble/python-neo/issues/1349#issuecomment-2183349170

Plus, some that I got in the CI on spikeinterface.

**Comment by h-mayorquin** [comment]
Another problem at the base:

https://github.com/NeuralEnsemble/python-neo/issues/1366

Would be good to get some data for this case @bendichter

**Comment by h-mayorquin** [comment]
OK, I have reproduced the windows error here in the CI.

This is good. 

For Mac, I will first try to set the right environment variable but we might also need to change the logic to access the ddl on neo:

https://github.com/NeuralEnsemble/python-neo/blob/1a7f60e2d75176b6df00fd7a2d1344772d223174/neo/rawio/plexon2rawio/plexon2rawio.py#L108-L117

Let's try.
