### ISSUE TITLE
[Feature]: CSVInterface

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#205]
### What would you like to see added to NeuroConv?

It's pretty common that we receive CSVs and need to add them to an NWB File. We could parse them using `pandas`, and pass all the input args that pandas supports for skipping rows, labeling columns, etc. Then we could start by assuming we are creating a `trials` table, then generalize to other `TimeIntervals` tables, then generalize to other `DynamicTables`.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
First implementation added in #252 

Future interfaces could pull from other ASCII-like files (like a structured `.txt` or structs in `.mat` files) and could write to `DynamicTables`, not just `TimeIntervals`

**Comment by CodyCBakerPhD** [comment]
I was keeping this one open since the `CsvDynamicTable` interface doesn't exist yet (only `TimeIntervals`), but as long as we remember to make it in the future fine to keep closed
