### ISSUE TITLE
[New Format]: MCSRaw

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#214]
### What format would you like to see added to NeuroConv?

"MCSRaw"

### Does the format have any documentation?

Couldn't find any

### Existing APIs for format

Neo and SI

### Do you have any example files you are willing to share?

https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/rawmcs

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Maybe this is it? https://www.multichannelsystems.com/downloads/software

@JuliaSprenger Would you happen to know what the overlap is between MCSRaw and NeuroShare? Are these both `ecephys` formats?

**Comment by JuliaSprenger** [comment]
MCSRaw seems to be specific to the MC_DataTool and MultiChannelSystems setups. NeuroShare is a generic format for which any system can provide a dll to read and write to (and for which MultiChannelSystems provided an implementation).
