### ISSUE TITLE
[Feature]: SpikeGLXConverter

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#243]
### What would you like to see added to NeuroConv?

Right now we have three different interfaces associated with SpikeGLX: Recording, LFP, and soon we will have Nidaq. This is great in the sense that it provides maximum flexibility, but it creates another layer of complication for the user, most of whom just wants to build a conversion script with as little effort as possible.

I would like to propose a solution: `SpikeGLXInterface`, which takes as input the parent directory and assumes a standard filepath to the .nidaq, .ap.bin, and .lf.bin files. It's constructor could include binary flags `include_ap`, `include_lf`, and `include_nidq`, which would all be True by default. It also exposes attributes `.ap_interface`, which returns the `SpikeGLXRecordingInterface`, `.lf_interface` which returns the `SpikeGLXLFPInterface`, and `.nidq`.

It would be even better if we could finally take the last steps in making `NWBConverter` a subtype of `BaseDataInterface` so we could construct this as a simple `NWBConverter` and use it in combination with other interfaces

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
I would just call this a `SpikeGLXConverter` and have it contain those other interfaces. Only major feature we would then need to add/test is the ability for `NWBConverters` to contain other NWBConverters and recurse metadata/conversion calls down through all the component interfaces
