### ISSUE TITLE
[Feature]: phase out spikeextractor_backend

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#263]
### What would you like to see added to NeuroConv?

can we start putting a deprecation warning on the old backend? I don't think it is being used anymore and I'd rather not continue to support it.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Plan is to move on this as soon as our last SE-only backend https://github.com/SpikeInterface/spikeinterface/pull/1158 is merged in SI
