### ISSUE TITLE
[Testing]: check docstrings for consistency

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#284]
### What would you like to see added to NeuroConv?

Replaces the dynamic parsing proposal of #278

Add simple tests that check the docstring description of both upstream arguments that are copied and propagated as well as internal repeated arguments

very low priority, however

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
Does the recently merged https://github.com/catalystneuro/neuroconv/pull/771 relates to this?

**Comment by CodyCBakerPhD** [comment]
#771 leverages any consistency already there, but doesn't actually check for it and would benefit from this

Pydocstyle in #276 would be sort of first step, then beyond that possible what Paul did in ROIExtractors CI

**Comment by h-mayorquin** [comment]
Maybe @pauladkisson would like to take on this one then given he has some experience already.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Are you putting your foot down on this one as being too annoying? Note that it is a feature utilized by the schema inference (and thus adds descriptions to all fields on the GUIDE without manual shema injections at the class level)

**Comment by h-mayorquin** [comment]
Let's discuss this in our meeting. It is more that I have not had the time and the priority is low.

**Comment by h-mayorquin** [comment]
These could be three things
* First this started as a series of checks to ensure that repeated arguments (e.g. the description of verbose) are consistent across all uses on the database. 
* The docstring exists.
* Consistency of style (do we comply with numpy style).

The relationship with the guide is that it uses the descriptions in the json schema. So they being consistent helps but should not be a concern here.

**Comment by h-mayorquin** [comment]
> First this started as a series of checks to ensure that repeated arguments (e.g. the description of verbose) are consistent across all uses on the database.

@pauladkisson pointed out in the meeting of 2024-08-27 that there might not be a way to automatize this in a resaonble way. The main reason is that maybe some docstrings should be different even if they cover the same behavior if they can add context that is relevant on that specific case (e.g. verbose prints different things in different interfaces and the docstring could describe what it does on each interface).

I think that the genesis of the consistency idea was when were thinking about conversion options and we thought that they should be more or less the same everywhere. Maybe that assumption was wrong for the ssame reasons that @pauladkisson points out. Anyway, I am happy to mark this as closed once https://github.com/catalystneuro/neuroconv/pull/1029 and https://github.com/catalystneuro/neuroconv/pull/1028 are merge.

**Comment by pauladkisson** [comment]
Closing this since the relevant PRs have been closed.
