### ISSUE TITLE
[Feature]: increasing modularity of tests

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#289]
### What would you like to see added to NeuroConv?

Right now, we have one test for all interfaces and we use `parameterized` to iterate over all of the interfaces. This worked great at first, but now that we have 36+ supported interfaces it has become a bit cumbersome. Having one identical test for all DataInterface classes makes it difficult to build in customized behavior for any individual class. This structure also makes it difficult for externally contributed DataInterface classes to use our test structure.

At its current size, I think an object-oriented approach may be more appropriate. We would have one `DataInterfaceTest` abstract class that defines the I/O tests that are the same testing for all `DataInterface` classes and would allow for individual child classes to implement specialized tests for each interface. This would have a few benefits over the current structure:
1. We could move the metadata extraction tests to methods of these classes, unifying tests for each DataInterface into a single class.
2. All tests for a given format, including the I/O and metadata tests, would only require one read operation.
3. We would have the freedom to move tests that correspond to different source formats into different files.
4. If the `DataInterfaceTest` class is implemented in a `neuroconv.testing` module, DataInterfaces contributed from an external repository would be able to import it and use it to build their own tests.
5. We are accumulating a lot of flow control logic in the current pattern and I think this would just be a lot more readable.

Any downsides to this besides the obvious labor in refactoring?

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
I think this is a good idea. This is sketch I wrote just right now porting the cod that we have in the gin tests (I have an instance for RecordingExtractor and I expect we would have one for Sorters, Image and Segmentation Extractors as well).

Do you have in mind something like this?

```python
from abc import ABC, abstractmethod

class TestBaseDataInterface(ABC):
    

    @abstractmethod
    def test_initialization(self, interface, interface_init_kwargs):  
 
        pass
    
    @abstractmethod
    def test_round_trip_to_nwb(self,  conversion_options, metadata, nwbfile_path):
        """
        Write to NWB and read back in with the NWBRecordingExtractor. Compares the recorders for equality.
        """
        pass
    
    @abstractmethod
    def test_metadata_extraction(self, expected_metadata):
        """
        Comparest expected metadata to extracted metadata
        """
        pass
    
    
class TestEcephysRecordingInterface(TestBaseDataInterface):
    
    def test_initialization(self, interface, interface_init_kwargs):
        
        # No assertions here, something else?
        self.interface = interface(interface_init_kwargs)
    
    def test_round_trip_to_nwb(self, conversion_options, metadata, nwbfile_path):
        """
        Write to NWB and read back in with the NWBRecordingExtractor. Compares the recorders for equality.
        """
        # Metdata should be passed with time information for example
        self.metadata = deepdictupdate(self.interface.get_metadata(), metadata)
        self.metadata.run_conversion(nwbfile_path=nwbfile_path, overwrite=True, metadata=metadata)
        recording = self.metadata.data_interface_objects["TestRecording"].recording_extractor

        es_key = self.metadata.get_conversion_options()["TestRecording"].get("es_key", None)
        electrical_series_name = metadata["Ecephys"][es_key]["name"] if es_key else None
        if not isinstance(recording, BaseRecording):
            raise ValueError("recordings of interfaces should be BaseRecording objects from spikeinterface ")
        
        # NWBRecordingExtractor on spikeinterface does not yet support loading data written from multiple segment.
        if recording.get_num_segments() == 1:

            # Spikeinterface behavior is to load the electrode table channel_name property as a channel_id
            nwb_recording = NwbRecordingExtractor(file_path=nwbfile_path, electrical_series_name=electrical_series_name)
            if "channel_name" in recording.get_property_keys():
                renamed_channel_ids = recording.get_property("channel_name")
            else:
                renamed_channel_ids = recording.get_channel_ids().astype("str")
            recording = recording.channel_slice(
                channel_ids=recording.get_channel_ids(), renamed_channel_ids=renamed_channel_ids
            )

            # Edge case that only occurs in testing, but should eventually be fixed nonetheless
            # The NwbRecordingExtractor on spikeinterface experiences an issue when duplicated channel_ids
            # are specified, which occurs during check_recordings_equal when there is only one channel
            if nwb_recording.get_channel_ids()[0] != nwb_recording.get_channel_ids()[-1]:
                check_recordings_equal(RX1=recording, RX2=nwb_recording, return_scaled=False)
                if recording.has_scaled_traces() and nwb_recording.has_scaled_traces():
                    check_recordings_equal(RX1=recording, RX2=nwb_recording, return_scaled=True)
                    
    def test_metadata_extraction(self, expected_metadata):
        """
        Comparest expected metadata to extracted metadata
        """
        
        expected_electrical_series_metadata = expected_metadata["Ecephys"]["ElectricalSeries"]
        expected_electrodes_metadata = expected_metadata["Ecephys"]["Electrodes"]
        expected_electrode_groups_metadata = expected_metadata["Ecephys"]["ElectrodeGroups"]
        
        assert self.metadata["Ecephys"]["ElectricalSeries"] == expected_electrical_series_metadata
        assert self.metadata["Ecephys"]["Electrodes"] == expected_electrodes_metadata
        assert self.metadata["Ecephys"]["ElectrodeGroups"] == expected_electrode_groups_metadata
```

**Comment by bendichter** [comment]
@h-mayorquin 

`TestBaseDataInterface(ABC)` would inherit from `unittest.TestCase` [source](https://docs.python.org/3/library/unittest.html#unittest.TestCase)

The rest looks right. I'm on the fence about whether we'd want `test_metadata_extraction` to be a required method since it won't be defined in some cases.

**Comment by CodyCBakerPhD** [comment]
Closed now with the completion of all the new `neuroconv.testing` mixins
