### ISSUE TITLE
[Feature]: reorganize SpikeGLX interfaces

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#290]
### What would you like to see added to NeuroConv?

Right now we have:

ap -> `SpikeGLXRecordingInterface`
lf -> `SpikeGLXLFPInterface`
nidq -> `SpikeGLXNIDQInterface`

This scheme is useful because each interface uses the appropriate extractor in the standard way.

The main problem with this layout is that it is too difficult for a user to create a conversion that includes all 3. Only 1 of them is the "recording" interface, but from a NeuroConv perspective they really all should be, because they are all data produced by a SpikeGLX recording. The ap is the stream that generally goes into spike sorting pipelines, but that doesn't make it more of a recording than lf or nidq. It often makes sense to differentiate between a recording and an LFP stream because often LFP is derived from the raw unfiltered stream, but that is not the case here. In this case, I think having a "recording" that does not include all three is misleading.

I would like to propose the following change:

ap -> `SpikeGLXAPInterface`, which creates an ElectricalSeriesAP (renaming the current SpikeGLXRecordingInterface)
lf -> `SpikeGLXLFInterface`, which creates an ElectricalSeriesLF (renaming the current SpikeGLXLFPInterface)
nidq -> `SpikeGLXNIDQInterface` (this is unchanged)

all three together -> `SpikeGLXRecordingInterface`

The `SpikeGLXRecordingInterface` would take as input the entire directory of the spikeglx recording and flags for what streams to include, defaulting to including all of them. It would automatically infer the paths of the ap, lf, and nidq streams and would load the data and metadata and do the conversion very similarly to how an NWBConverter works. If there is something non-standard, like a different folder structure for the spikeglx data, a user can always go down to the individual interfaces. The conversion gallery would continue to show the `SpikeGLXRecordingInterface` in its default configuration, which would convert all three streams.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
> ap -> SpikeGLXAPInterface / lf -> SpikeGLXLFInterface

Yes, I think this is perfectly fine. SpikeGLX is a unique format in that respect and it would be worth it to clarify the AP/LF band nomenclature as distinct from other typical recording/processing approaches.

A question similar to this that I heard a lot SFN22 was 'SpikeGLX? What is that?' or 'So you don't support Neuropixels?'.

Only the technical people seem to know automatically what SpikeGLX is (the software/GUI/format) but a lot of people know what Neuropixels probes are.

Should we also take this opportunity to either (a) rename to `Neuropixels{AP or LF or NIDQ}Interface`, or (b) add extra interfaces `Neuropixels{AP or LF or NIDQ}Interface` that simply alias to `SpikeGLX{AP or LF or NIDQ}Interface`



> The SpikeGLXRecordingInterface would take as input the entire directory of the spikeglx recording and flags for what streams to include, defaulting to including all of them. 

From #243 the proposed `SpikeGLXRecordingInterface` here really ought to be a `SpikeGLXNWBConverter`

Also, keeping the name `SpikeGLXRecordingInterface` but changing its call behavior and purpose would constitute a more confusing deprecation than just changing its name (a deprecation warning + alias to a separate interface, then eventually remove it)



> It would automatically infer the paths of the ap, lf, and nidq streams and would load the data and metadata and do the conversion very similarly to how an NWBConverter works.

An interface handles I/O along a particular data stream

NWBConverters handle communication/aggregation of multiple data streams

I agree this would be very convenient, but we should maintain our typical API structure and make it a Converter class

The only change this requires as discussed in #243 is to allow NWBConverters to be passed into NWBConverters, which shouldn't be too hard but will require a bit of time to thoroughly test

**Comment by CodyCBakerPhD** [comment]
> In particular, doing the input validation while doing the mapping of the paths.

Ah... if the thinking was to maintain the `source_data` structure at each level like

```python
source_data = dict(
    InterfaceA=dict(file_path=...),
    SubConveterA=dict(
        source_data=dict(
            SubInterfaceA=dict(file_path=...),
            SubInterfaceB=dict(file_path=...),
        )
    )
)
```

then yes that gets ugly fast...

I was thinking of a simpler `__init__` override for the `SpikeGLXNWBConverter` though,

```python
source_data = dict(
    InterfaceA=dict(file_path=...),
    SubConveterA=dict(
        folder_path="folder_with_many_common_streams",
        streams_to_load: List[str] = ["AP", "LF", "NIDQ"]),
)
```

validating that should be very easy

**Comment by bendichter** [comment]
yes, I was going for option 2. It was more difficult than I expected. Maybe there's a simple solution that I am not seeing
