### ISSUE TITLE
[Feature]: take control of es_key

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#297]
### What would you like to see added to NeuroConv?

RecordingInterface classes should manage their own es_key

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
This issue requests removal of `es_key` from the call signature of all `RecordingInterface.run_conversion` methods, instead hard-coding the `es_key` passed to the `neuroconv.tools.spikeinterface.write_recording` to whatever the `es_key` happens to be set as for that interface's metadata

I don't think this would cause any issues with interface usage, but I wanted to check with @weiglszonja and @h-mayorquin to see if you guys might recall any times when you may have needed to use a custom override of that argument within a conversion script
