### ISSUE TITLE
[Documentation]: Combine /documentation into /docs

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#3]
### What would you like changed or added to the documentation and why?

@h-mayorquin or @weiglszonja, could one of you tackle this when you have the time?

Basically just merge the content of the `.md` file + `.png` found in https://github.com/catalystneuro/neuroconv/tree/main/documentation into the Readthedocs folder `/docs` so it's centralized.

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by weiglszonja** [comment]
I'm happy to do it, but I can only start this on Monday probably (or Sunday late-afternoon if urgent).
