### ISSUE TITLE
[Feature]: Interfaces should know their starting time and rate vs. irregular timestamps

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#302]
### What would you like to see added to NeuroConv?

A related issue to PR #237, currently our handling of `starting_time` shifts of a regular series is inefficient - often, the underlying time vector attached to `Extractors` is adjusted to start from the specified `starting_time`, but that triggers the creation of a full time vector from rules similar to `np.arange(number_of_frames) / rate + starting_time`, which is quite wasteful instead of just storing the scalar `starting_time` + `rate` separately

Our tools account for this when writing to NWB - we do not write NWB files with `timestamps` fields which would be regular and instead convert those to `starting_time` and `rate` - but the computations involved in making that decision are a bit wasteful if you knew it was regular or irregular ahead of time

The current method `get_timestamps`, for an extractor-based interface, could be adapted to `get_times` or `get_timings` and would look like

```python
def get_times(self) -> dict:
    if (
        not self.extractor.has_time_vector()  # otherwise, this means it was explicitly set and should be assumed to be irregular
        and self.starting_time is not None
    ):
        return dict(
                       starting_time=self.starting_time,
                       rate=self.extractor.get_sampling_frequency(),  # is always available
                   )
    else:
        return dict(timestamps=self.get_times())
```

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
I think this should be solved at the spikeinterface level, would you be OK with closing this @CodyCBakerPhD ?
