### ISSUE TITLE
[Feature]: Make test suite require fewer dependencies

### ISSUE THREAD

**Issue by TheChymera** [catalystneuro/neuroconv#305]
### What would you like to see added to NeuroConv?

It would be cool to make the test suite more accessible.

### Is your feature request related to a problem?

I get numerous test failures, mainly due to the test suite having a large and dependency graph specific to the package, but also due to missing test data.

Here is the [full build and test log](https://ppb.chymera.eu/1415d6.log).

(1) Is there any way to download the test data separeatly? Going by the log, I thought it might be under https://github.com/catalystneuro/ephy_testing_data but there's nothing there

(2) would it be possible for the test suite to just skip tests if optional dependencies are not installed? 

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
@TheChymera Can you give the [README section for developers](https://github.com/catalystneuro/neuroconv#for-developers) a look through and let us know what specifically fails when following those instructions?

Perhaps we should add some extra clarification to that (and the main read the docs...) describing how the tests are modularized. What I would say is, anyone should be able to do `pip install -e local_copy_of_neuroconv` followed by `pytest neuroconv/tests/test_minimal`. 

Anyone running the blanket `pytest` over the entire suite is intended to follow full setup instructions, but there is honestly little reason for that outside of the CI and core development.

If you're looking to test something like the spikeinterface write tools, I'd instead suggest installing with `neuroconv[ecephys]` + `pytest tests/test_ecephys`, which will also not require any local data to run.



> (2) would it be possible for the test suite to just skip tests if optional dependencies are not installed?

We used to do that, but it led to silent problems accumulating in the CI (which would then skip tests that it ought to have been running).

Explicit is better than implicit here - the intended behavior of the package is indeed to fail if you try running something that requires secondary installations which are not available.

**Comment by TheChymera** [comment]
@CodyCBakerPhD ok, the minimal tests pass, so do `tests/test_ecephys`.

I do however get some issues from `test/test_ophys`, which don't appear to be related to missing data. Any ideas what this could be about? https://ppb.chymera.eu/75c6f6.log

**Comment by CodyCBakerPhD** [comment]
@TheChymera I have no idea other than maybe to try changing those tests to use `assert_array_almost_equal` instead of exactly equal, but it looks like its also complaining about a shape issue?

Are you able to reproduce the issue locally?
