### ISSUE TITLE
[Bug]: concatenate spike data from multiple probes using Phy_sorting_interface discards information

### ISSUE THREAD

**Issue by Diirkk** [catalystneuro/neuroconv#330]
### What happened?

Tried to combine spike data from multiple probes suing Phy_sorting_interface (spike sorted separately, and stored in separate files/folders). The output .nwb file contains values from one probe only (potential indexing issue).

### Steps to Reproduce

```python
from dateutil import tz
from neuroconv import ConverterPipe
from neuroconv.datainterfaces import SpikeGLXRecordingInterface, PhySortingInterface

# For this interface we need to pass the location of the ``.bin`` file. Change the file_path to the location in your system
interface_spikeglx_1 = SpikeGLXRecordingInterface(file_path=path_raw, verbose=False)
interface_spikeglx_2 = SpikeGLXRecordingInterface(file_path=path_raw, verbose=False)


phy_sorting_interface_brain_area_1 = PhySortingInterface(folder_path=path_phy_PFC, verbose=False) #PFC
phy_sorting_interface_brain_area_2 = PhySortingInterface(folder_path=path_phy_HPC, verbose=False) #HPC

# number of observations for labels (below)
num_units_area_1 = phy_sorting_interface_brain_area_1.sorting_extractor.get_num_units()
num_units_area_2 = phy_sorting_interface_brain_area_2.sorting_extractor.get_num_units()

# add brain area label
phy_sorting_interface_brain_area_1.sorting_extractor.set_property(key="brain_region", values=["PFC"] * num_units_area_1)  # PFC for example
phy_sorting_interface_brain_area_2.sorting_extractor.set_property(key="brain_region", values=["HPC"] * num_units_area_2)  # V1 for example


num_channels = 384 
interface_spikeglx_1.recording_extractor.set_property(key="group_name", values=np.array(["Neuropixels shank 1"] * num_channels))
interface_spikeglx_2.recording_extractor.set_property(key="group_name", values=np.array(["Neuropixels shank 2"] * num_channels))

interface_spikeglx_1.recording_extractor.set_property(key="brain_region", values=["PFC"] * num_channels)  # PFC for example
interface_spikeglx_2.recording_extractor.set_property(key="brain_region", values=["HPC"] * num_channels)  # HPC for example

 # Now that we have defined the two interfaces we pass them to the ConverterPipe which will coordinate the
 # concurrent conversion of the data
converter = ConverterPipe(
    data_interfaces=[
        interface_spikeglx_1,
        interface_spikeglx_2,
        phy_sorting_interface_brain_area_1,
        phy_sorting_interface_brain_area_2
    ],
    verbose=False
)

# Extract what metadata we can from the source files
metadata = converter.get_metadata()
# For data provenance we add the time zone information to the conversion
session_start_time = metadata["NWBFile"]["session_start_time"].replace(tzinfo=tz.gettz("UK"))
metadata["NWBFile"].update(session_start_time=session_start_time)

# Choose a path for saving the nwb file and run the conversion
conversion_options = dict(
    SpikeGLXRecordingInterface001=dict(write_electrical_series=False),
    SpikeGLXRecordingInterface002=dict(write_electrical_series=False)
)


converter.run_conversion(nwbfile=nwbfile, metadata=metadata, conversion_options=conversion_options)


# write NWB file
```

### Operating System

Windows

### Python Executable

Python

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Do you remember what the intended way of appending units onto the units table was, when they come from different sorting extractors?

For electrodes, we simply have to change the channel group for the recording extractors of different devices, but as I recall the sorting extractor did not have such a 'group' option did it?

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 

> For electrodes, we simply have to change the channel group for the recording extractors of different devices, but as I recall the sorting extractor did not have such a 'group' option did it?

We don't have a working way of doing this. The property `electrodes` is used to accomplish this when the `add_units_table` is called from within `add_waveforms`.  However, when this workflow is used in the same fashion as `add_electrode` above the code fails (I tested).

Diggin depper I can see that we have an inconsistency in behavior between `add_electrodes` and `add_units`. 
For `add_electrodes`, disambiguation functionality is achieved by adding a property to the recording (`group_name` as you do above) and then `add_electrodes` automatically takes care of disambiguating based on `channel_name` AND `group`. For `add_units`  I this is implemented with the `unit_electrode_indices` argument in the [add_units](https://github.com/catalystneuro/neuroconv/blob/812e6a134569534583a7025cb9df1ba07f013a6e/src/neuroconv/tools/spikeinterface/spikeinterface.py#L875-L889) function.

We should make the two functions work in the same way. I personally think the solution of `add_electrodes` is better. That is, I think we should pick a property in the sorter that can be used to disambiguate. Let's discuss this on the incoming meeting as it will be easier to coordinate with @alejoe91 and see if we are not missing something obvious.

**Comment by h-mayorquin** [comment]
So right now we have for the waveform pipeline:

```python
    electrode_group_indices = get_electrode_group_indices(recording, nwbfile=nwbfile)
    unit_electrode_indices = [electrode_group_indices] * len(sorting.unit_ids)
```

The first line gets the indexes in the electrodes table of hte nwbfile for corresponding to the recording groups. Then the second line just creates a large list of list with those indices. That is, every unit is assigned all the electrodes from the recording.

**Comment by h-mayorquin** [comment]
This should be solved by now. Sorry, this took so long.
