### ISSUE TITLE
Is `add_electrical_series` module adding incorrect conversion information to the nwbfile?

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#34]
So, the following recording extractor has no information about its units:

```python
from pynwb.file import NWBFile
from neuroconv.tools.spikeinterface import add_electrical_series
from spikeinterface.core.testing_tools import generate_recording
from datetime import datetime

durations = [3]
sampling_frequency = 1.0
recording = generate_recording(num_channels=2, durations=durations, sampling_frequency=sampling_frequency)
recording.has_scaled_traces()
```
Its output is 
`False`

However, if we use the method `add_electrical_series` with this recorder the resulting ElectricalSeries object in the nwbfile looks like this:

```python
testing_session_time = datetime.now().astimezone()
nwbfile = NWBFile(
            session_description="session_description1", identifier="file_id1", session_start_time=testing_session_time
        )



add_electrical_series(recording=recording, nwbfile=nwbfile)

acquisition_module = nwbfile.acquisition
electrical_series = acquisition_module["ElectricalSeries_raw"]
electrical_series
```
Output:
```python
ElectricalSeries_raw pynwb.ecephys.ElectricalSeries at 0x139998292246144
Fields:
  comments: no comments
  conversion: 1e-06
  data: <hdmf.backends.hdf5.h5_utils.H5DataIO object at 0x7f53abe9afd0>
  description: Raw acquired data
  electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
  offset: 0.0
  rate: 1.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: volts
```

So, we have written the value of `conversion=1e-06` which I think is incorrect. As I understand it, that conversion factor there means that **if the stored data were to be multiplied by `1e-06` then the result would be the data in units of volts**. But the latter we can not guarantee.

## What to do?
Maybe when the `spikeinterface` recording extractor `has_scaled_traces() == False` we should just throw a warning and then add in the comments that the time series contained there does not have concrete units.

@bendichter @CodyCBakerPhD What do you think? Is there something I am missing?

**Comment by CodyCBakerPhD** [comment]
Also be sure to check the `channel_conversion` factor, which can sometimes be written in addition to a global scalar factor of `1e-6`. Matrix equation to volts then is `data_in_volts = data_in_ints * channel_conversion * conversion.

Doesn't look like the case here, though, but the key thing is you cannot change the units involved in an ElectricalSeries since they are clamped to Volts: https://pynwb.readthedocs.io/en/stable/pynwb.ecephys.html#pynwb.ecephys.ElectricalSeries

As such if we ever did encounter a non-toy extractor that does not have any scaling factor, yeah we should probably just throw an error and require them to provide that conversion information by setting it in the extractor.

I think the assumption of `1e-6` was legacy from `spikeextractors` where it was a bit more common to find extractors without conversion factors. But now that `gain_to_uV` is more prevalent we should expect it more often

**Comment by CodyCBakerPhD** [comment]
Defining shapes - for N frames and M channels `$data_in_volts, data_as_extracted \in \R^{N \times M}$`, `$channel_conversion \in \R^{M \times 1}$` and `$conversion, offset \in \R$`.

`$data_in_volts = data_as_extracted \times (\mathbb{I}_M \times channel_conversion) * conversion + offset \times \mathbb{1}_{1 x M} \times \mathbb{I}_M$` where `\times` is the matrix product and `*` is the scalar product.

Make sense?

**Comment by h-mayorquin** [comment]
I don't think that your data latext is rendering very well. 

I did an attempt but there is something failing:
Defining shapes - for N frames and M channels `data_in_volts`, `data_as_extracted` $\in R^{N \times M}$, channel_conversion $\in R^{M \times 1}$ and conversion, offset $\in R$.

`data_in_volts` = `data_as_extracted` $\times$ (\mathbb{I}_M $\times$ `channel_conversion`) * `conversion` + `offset` $\times$ $\mathbb{1}_{1 x M} \times \mathbb{I}_M$
where $\times$ is the matrix product and `*` is the scalar product.

---
Anyway, you just wanted to clarify that `channel_conversion` is a vector of length the number of units, right?

**Comment by h-mayorquin** [comment]
Yes, `number_of_channels` not number of units.

Check this out:
https://github.blog/2022-05-19-math-support-in-markdown/

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
The offsets of the recording extractor object can be non-uniform as well as the gains. If both gains and offset are non-uniform I think that there is no solution for making the data fit. That is, no values of `channel_conversion`, `conversion` and `offset` can be found that will make the data equal after the adequate transformations described above. Have you thought about this?

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Yes a recording extractor object can have that but it's unusual to find for a single ecephys recording. Usually, non-uniform properties like that indicate non-ecephys channels or different probes that could then be read/written as different series (each series having uniform properties)

The NWB schema only supports scalar offsets ATM so if we do try to write a recording extractor with `write_recording` that does not have uniform offsets, we should probably throw an error

**Comment by h-mayorquin** [comment]
Would you say the same applies for variable gains in recording extractor objects? 
I am asking all of this because I am thinking on scenarios to test.

**Comment by CodyCBakerPhD** [comment]
> Would you say the same applies for variable gains in recording extractor objects?

For a single non-multi extractor, yes, but one could think of a MultiChannelRecording that spans multiple distinct probes with different types of electrode properties, yes that would be a case for non-uniform `channel_conversion` (still blockwise-uniform though over the probes). That said I haven't seen that before. And offsets likewise are mostly used for translating unsigned to signed data or for special types of channels like temperature/pressure - the latter we could just write different blocks of series corresponding to each offset, and for the former, they always should be different series.

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD @bendichter 

I think we are writing data to electrical series in the wrong units or in the wrong way. Check this out. This is a recorder with actual gains and offsets:

```python
from pynwb.file import NWBFile
import numpy as np
from neuroconv.tools.spikeinterface import add_electrical_series
from spikeinterface.core.testing_tools import generate_recording
from datetime import datetime

durations = [3]
sampling_frequency = 1.0
recording = generate_recording(num_channels=2, durations=durations, sampling_frequency=sampling_frequency)
gains = [2, 2]
offset = [0, 0]
recording.set_channel_gains(gains)
recording.set_channel_offsets(offset)
recording.has_scaled_traces()
True

testing_session_time = datetime.now().astimezone()
nwbfile = NWBFile(
            session_description="session_description1", identifier="file_id1", session_start_time=testing_session_time
        )



add_electrical_series(recording=recording, nwbfile=nwbfile, iterator_type=None, write_scaled=False)

acquisition_module = nwbfile.acquisition
electrical_series = acquisition_module["ElectricalSeries_raw"]

# spikeinterface returns traces in microvolts
conversion_factor = electrical_series.conversion
print("conversion factor", conversion_factor)
print("channel converison", electrical_series.channel_conversion)
print("offset scalar", electrical_series.offset)
```
Output:
```
conversion factor 2e-06
channel converison None
offset scalar 0.0
```

To convert the data extracted from the spikeinterface recorder to uV you need to multiply by the gains (2, in this case) and then add the offset (this is what `write_scaled` as an argument for a `get_traces` does). By default, now in `add_electrical_series` the data is written as it is from the `recorder_extractor` object (i.e. `write_scaled=False` by default). 

OK, so what are we writing above? my understanding is that we are telling the user that if they took the data and multiplied by (2 e-06) they will obtain units in Volts. However, as the data was stored as it is, when multiplied by the gain (2) it will become uV and then multiplied by e-06 it will become  picovolts instead.  

Am I misunderstanding something?

**Comment by h-mayorquin** [comment]
I think that this should not fail with the code above:
```python
import numpy as np
# spikeinterface returns traces in microvolts
traces_in_volts = recording.get_traces(segment_index=0, return_scaled=True) * 1e6
extracted_data_in_volts = electrical_series.data[:] * conversion_factor + electrical_series.offset
np.testing.assert_array_almost_equal(traces_in_volts, extracted_data_in_volts) 
```
But it does.

**Comment by CodyCBakerPhD** [comment]
I have a single `int16` data value from the recording of `15`. I scale that to $\mu V$ by multiplying by 2. My data value is now seen to be $30 \mu V$. That is equivalent to $30e^{-6} \ V$

**Comment by h-mayorquin** [comment]
Yes, makes sense. My mistake, I got my conversion factor inversely.

**Comment by h-mayorquin** [comment]
> Yes a recording extractor object can have that but it's unusual to find for a single ecephys recording. Usually, non-uniform properties like that indicate non-ecephys channels or different probes that could then be read/written as different series (each series having uniform properties)
> 
> The NWB schema only supports scalar offsets ATM so if we do try to write a recording extractor with `write_recording` that does not have uniform offsets, we should probably throw an error

@CodyCBakerPhD 
I implemented this here but I have one of the gin tests is failing precisely because of this. The CED data does actually have different offsets per channel as we discussed on:
https://github.com/catalystneuro/neuroconv/issues/8

**Comment by CodyCBakerPhD** [comment]
> I implemented this here but I have one of the gin tests is failing precisely because of this. The CED data does actually have different offsets per channel as we discussed on:

Yep, that is because those different channels are non-neurological so the only ones we want to write to an NWB ElectricalSeries are the consistent Rhd channels - the point still being, you don't need to indicate that ahead of time, just subset the recording extractor after successful `__init__` of all the channels to only use the Rhd ones.

Also, I'm surprised Intan doesn't have an issue since it is the one that uses offsets, which from https://github.com/catalystneuro/neuroconv/issues/7 are not yet operating round-trip?

**Comment by h-mayorquin** [comment]
Interesting. Yes, the nwb extractor from spikeinterface should be updated.

**Comment by CodyCBakerPhD** [comment]
> the nwb extractor from spikeinterface should be updated.

@h-mayorquin Any way we could get that in before the upcoming SI release?

@alejoe91 @samuelgarcia What is the ETA looking like for that?

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
I will make it a priority.
