### ISSUE TITLE
[Documentation]: use pydata theme

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#347]
### What would you like changed or added to the documentation and why?

Lots of leading numerical computing Python libraries are using [the PyData Theme for readthedocs](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html), and I think it's a really nice style. Let's look into adopting this style. I tried just naively applying it and it looks like this will take a bit of reorganization of the docs to make it look good.

* API documentation will need to re reorganized so that API is on the top level and all API documentation are beneath it
* The catalog should be moved somewhere else. Maybe at the end of the user guide?

### Do you have any interest in helping write or edit the documentation?

Maybe

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Yes, that does look good. Much better than RTD basic
