### ISSUE TITLE
[Feature]: Clarify Suite2P object names

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#378]
### What would you like to see added to NeuroConv?

Posted from discussion with @jeromelecoq  in this conversion on PyNWB: https://github.com/NeurodataWithoutBorders/pynwb/issues/1667#issuecomment-1474716708

Here is a snapshot of HDFView looking at an example of a Suite2P output from our testing suite

![image](https://user-images.githubusercontent.com/51133164/226113823-a49c2749-73cd-4462-8199-8d18c04b9ae0.png)

The 'RoiResponseSeries' at the same level of the other traces is not clear what type of 'response' it is supposed to be, and how it is different from the Neuropil and Deconvolved

What are some other names or representations we could use to make it clear that the 'RoiResponseSeries' is the baseline flourescence (which I assume it is - should also probably double check that upstream with Suite2P)?

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
As our local ophys expert @alessandratrapani do you have any views on this one?

**Comment by CodyCBakerPhD** [comment]
We did something very much along these lines in the last year with Caiman, joint work with @pauladkisson 

I forget if that changed Suite2p at the same time though

**Comment by CodyCBakerPhD** [comment]
I will double check if this is still an issue in modern files and reopen if not. After @alessandratrapani and I took a look at the codebase I think the same fix we did for Caiman and others should apply to currently created Suite2P files and so this is no longer an issue

The 'RoiResonseSeries' should be annotated as 'Raw' in some form or another
