### ISSUE TITLE
[Feature]: Track suggested or common suffixxes per interface

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#381]
### What would you like to see added to NeuroConv?

Spiritual successor to #375, but for file suffixes

For folder formats, could collect and refer to all of the suffixes for all the files under the folder, such as `.ncs` for Neuralynx, `.npy` for Phy, etc...

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by bendichter** [comment]
It might be nice to also do input regex for file suffixes which would require us to match the suffix to the source arg is applies to. Then we could use this for two purposes:
1. It could be automatically added to the keywords to help with search
2. It could be automatically incorporated into the source_data_schema to constrain the form input fields

**Comment by h-mayorquin** [comment]
I think this is sorted with https://github.com/catalystneuro/neuroconv/pull/734/files.
