### ISSUE TITLE
Discussion: Unify `run_conversion` interfaces between base classes and `nwbconverter`

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#42]
As we have been using `run_conversion` directly from the interfaces lately I have been discussing this with @CodyCBakerPhD . I am opening this issue to have a template to discuss tomorrow.

I think that we should have a common set of arguments (i.e. unify the keyword arguments that control input-output). Here I mean things like passing an nwbfile or a save_path. Another one is over-write functionality.

Other important considerations listed in no particular order are:
* The base data interfaces do not perform any validation.
* Division of responsibilities between `spikeinterface` and `nwb-conversion-tools`. 

For reference, the signatures of all the `run_conversions` methods at the moment of writing this issue are:
```python
# NWB general
def run_conversion(
    self,
    metadata: Optional[dict] = None,
    save_to_file: Optional[bool] = True,
    nwbfile_path: Optional[str] = None,
    overwrite: Optional[bool] = False,
    nwbfile: Optional[NWBFile] = None,
    conversion_options: Optional[dict] = None,
)

# Sorting extractor
def run_conversion(
    self,
    nwbfile: NWBFile = None,
    metadata: dict = None,
    stub_test: bool = False,
    save_path: OptionalFilePathType = None,
    overwrite: bool = False,
    write_ecephys_metadata: bool = False,
):

# Recording extractor
def run_conversion(
    self,
    nwbfile: NWBFile = None,
    metadata: dict = None,
    stub_test: bool = False,
    starting_time: Optional[float] = None,
    use_times: bool = False,
    save_path: OptionalFilePathType = None,
    overwrite: bool = False,
    write_as: str = "raw",
    write_electrical_series: bool = True,
    es_key: str = None,
    compression: Optional[str] = "gzip",
    compression_opts: Optional[int] = None,
    iterator_type: Optional[str] = None,
    iterator_opts: Optional[dict] = None,
)

# Movie data interface
def run_conversion(
    self,
    nwbfile: NWBFile,
    metadata: dict,
    stub_test: bool = False,
    external_mode: bool = True,
    starting_times: Optional[list] = None,
    chunk_data: bool = True,
    module_name: Optional[str] = None,
    module_description: Optional[str] = None,
    compression: Optional[str] = "gzip",
    compression_options: Optional[int] = None,
):

# Imaging
def run_conversion(
    self,
    nwbfile: NWBFile = None,
    metadata: dict = None,
    overwrite: bool = False,
    save_path: OptionalFilePathType = None,
):

# Segmentation
def run_conversion(self, nwbfile: NWBFile, metadata: dict, overwrite: bool = False):


```

**Comment by h-mayorquin** [comment]
Another point discussed with @CodyCBakerPhD is that interfaces, like `NWBConverter` and `InterfacePipeline` should return the in memory nwbfile as well.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin How do you think the state of this is now? Much has changed since then

**Comment by h-mayorquin** [comment]
After we merge https://github.com/catalystneuro/neuroconv/pull/1016 I will be able to enable source data checks for the interfaces and then we can close this.

**Comment by h-mayorquin** [comment]
The source data checks for the interfaces still need to be enabled.
