### ISSUE TITLE
Automatic metadata extraction for remaining RecordingInterfaces

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#43]
@h-mayorquin Please add check boxes for what interfaces don't have much metadata extraction as of yet, thanks!

**Comment by h-mayorquin** [comment]
I will wait till I get to partake on an OpenEphys conversion to work into this.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin That could be a while - @weiglszonja did a lot of work on that in the last year, maybe consult with here and then we can call this done?

**Comment by h-mayorquin** [comment]
Let' close this. I was thinking that I would had a OpenEphys project this August so I could finish the ecephys part but that will have to wait. I think we can open some more specific issues in the future.
