### ISSUE TITLE
Add data interface for European Data Format (EDF) 

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#44]
A request from @bendichter today.

There is a reader in neo:
https://github.com/NeuralEnsemble/python-neo/blob/f62bd73bff79d84d3f4cca653b37c86064205a4e/neo/rawio/edfrawio.py

There is some gin testing data here:
https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/edf

**Comment by h-mayorquin** [comment]
Note for further reference. 
The data on gin contains artificial data. The generator script can be found in the repository:
https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/edf/generate_edf+C.py

```python
from pathlib import Path
from neo.rawio import EDFRawIO

file_path = Path("/home/heberto/ephy_testing_data/edf/edf+C.edf")
file_path.is_file()

neo_reader = EDFRawIO(filename=str(file_path))
neo_reader.parse_header()
header = neo_reader.header
header["signal_channels"]
```
The output is:
```python
array([('ch1', '0', 256., 'int16', 'mV', 0.00610352, 0., '0'),
       ('ch2', '1', 256., 'int16', 'uV', 0.00610352, 0., '0'),
       ('ch3', '2', 256., 'int16', 'pA', 0.00610352, 0., '0'),
       ('ch4', '3', 256., 'int16', '', 0.00610352, 0., '0'),
       ('ch5', '4', 256., 'int16', 'C', 0.00610352, 0., '0')],
      dtype=[('name', '<U64'), ('id', '<U64'), ('sampling_rate', '<f8'), ('dtype', '<U16'), ('units', '<U64'), ('gain', '<f8'), ('offset', '<f8'), ('stream_id', '<U64')]
```
It has different units but the same gains and offsets.

**Comment by CodyCBakerPhD** [comment]
It would be nice if it's possible to get examples of real data here - in particular, the EDF offsets in practice are quite a bit complicated and are the the main reason we finally included that as an attribute of all TimeSeries. See this old convo for context: https://nwb-users.slack.com/archives/C5XKC14L9/p1644881349651429

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 

Thanks for sharing that. Just for completeness and reference these is how the offsets and gains are calculated in the neo code:

```
 physical_range = sig_dict['physical_max'] - sig_dict['physical_min']
  # number of digital steps resolved (+1 to account for '0')
  digital_range = sig_dict['digital_max'] - sig_dict['digital_min'] + 1
  gain = physical_range / digital_range
  offset = -1 * sig_dict['digital_min'] * gain + sig_dict['physical_min']
```

Which account for the formula described on the slack conversation:
![edf](https://user-images.githubusercontent.com/6429509/181776331-3bffd70b-b694-41aa-a8a4-e38d0d4b43e4.jpg)

**Comment by h-mayorquin** [comment]
Now that #45 is merged we can close this.
