### ISSUE TITLE
IndexError when using TdtRecordingInterface

### ISSUE THREAD

**Issue by GMCadode** [catalystneuro/neuroconv#444]
Hello,
I get the following error when running the code for the TdtRecordingInterface object:
IndexError: list index out of range
 

The code that I try to run (currently from Spyder) is as follows based (with minor tweaks) on your provided tutorial for TDT conversion:

```python
from datetime import datetime
from dateutil import tz
from pathlib import Path
from neuroconv.datainterfaces import TdtRecordingInterface

# For this data interface we need to pass the folder_path with the location of the data
pnStr = "C:/DATAtemp/ET RO1 Preclinical/data-acquisition/20230505/Zebel-230505-112312"
pnPath = Path(pnStr)
# Change the folder_path to the location of the data in your system
interface = TdtRecordingInterface(folder_path=pnPath)
```

I'm also pretty new to python, so apologies if I'm missing something obvious. 
Thanks!

**Comment by CodyCBakerPhD** [comment]
Hi, welcome to NeuroConv!

Can you please post the entire traceback error message from where it starts, not just the final IndexError? It will help provide more context to pin down the issue.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin WDYT? Good to close?

**Comment by h-mayorquin** [comment]
Don't know enough about the latest developments on Tdt but given that the user did not come back we should close and open another issue if this resurfaces in the future.
