### ISSUE TITLE
Documentation of the API broke

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#46]
Hi, I just noticed that the API section for our documentation broke:

https://neuroconv.readthedocs.io/en/main/api/interfaces.ecephys.html

The only two recent changes were:
https://github.com/catalystneuro/neuroconv/pull/39
And
https://github.com/catalystneuro/neuroconv/pull/30

As it was working when this was merged:
https://github.com/catalystneuro/neuroconv/pull/31

I have not looked into it but maybe you have any quick ideas @weiglszonja  and @CodyCBakerPhD ?

**Comment by weiglszonja** [comment]
Sorry for the quality, I’m from the phone. So I was looking at the readthedocs build when they were merged, and neither looks good in the API section. There most be a commit or update that they share when it happened, but I didnt take a closer look for now. 
![
![52C44FFF-4D76-4E16-BC31-731C77DB631A](https://user-images.githubusercontent.com/24475788/181801623-5d0e213d-e45d-427e-998d-37099044a5cc.png)
Uploading 083C08FA-4C04-4F0D-BDAB-EB75FBC2CEE8.png…]()

**Comment by weiglszonja** [comment]
![886DFD04-8978-4500-B0C0-83ADABBEAF42](https://user-images.githubusercontent.com/24475788/181802418-7aa2856c-0e29-4a47-9abe-8581c187a982.png)
![AA748450-8EFD-4FC2-B245-25F548B1733F](https://user-images.githubusercontent.com/24475788/181802421-906e7fce-ad7a-404f-baf6-fdb7b6b2e344.png)

**Comment by weiglszonja** [comment]
I traced it back to #22 too:
https://neuroconv--22.org.readthedocs.build/en/22/api/interfaces.ecephys.html#blackrock-recording
