### ISSUE TITLE
What should `es_key` be for LFP  

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#461]
Looking at the current `BaseLFPExtractorInterface` the `es_key` seems to end on  `LF` instead of `LFP`:

https://github.com/catalystneuro/neuroconv/blob/5da7ab50bf1d6762fcbfa468ee22b0b05ebd6b17/src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py#L19

Is this like that for a reason or just a typo?

This is writing the final name of my series wrong in the current conversion.

**Comment by bendichter** [comment]
This matches the naming convention of SpikeGLX, but I don't recall seeing it used outside of that context.

**Comment by CodyCBakerPhD** [comment]
Looks like a mistake from #318, specifically https://github.com/catalystneuro/neuroconv/pull/318/files#diff-16dd01ce595755ecae8af2b7f80f440d8ff2670caeed509026a5d8a93934ac70R12

@h-mayorquin Can you fix it in the base? It was only intended for SpikeGLX
