### ISSUE TITLE
Would it be useful for our users if we supported a method chaining workflow?

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#473]
#455 adds `add_to_nwb` method for the interfaces.

I really like this because from the point of view of experimenentation it supports the following workflow:
```python
nwbfile = interface1.create_nwbfile(kwargs) 
nwbfile = interface1.add_to_nwbfile(kwargs)
# You can check what you added, debug, and once you are happy with this move forward
nwbfile = interface2.add_to_nwbfile(kwargs)
# You can check whaty ou added, debug and once you are happy with this move forward
...
nwbfile = interface5.add_to_nwbfile(kwrags)
interface5.write_to_nwbfile()  (# Not sure yet how we do this with #455 )
```
This is very nice for exploration and experimentation, plus it is necessary to move forward with https://github.com/catalystneuro/neuroconv/issues/441. At this stage though, this reminds me of [method chaining](https://en.wikipedia.org/wiki/Method_chaining) (1). Which leads me to the question, why no go even further and implement something like this:

```python
nwbfile_conversor = nwb_conversor(metadata)  # This can work as an initializer for an nwb-file in memory with basic metadata
nwbfile_conversor.add_interface(interface1)
nwbfile_conversor.add_interface(interface2)
nwbfile_conversor.write()  # <- writing / bounding / compression happens here
```

Where `nwbfile_conversor` (or another name) is just a wrapper of an nwbfile that implements `add_to_nwb` under the hood. Metod chaining is very pouplar for data transformation pipelines with the workflow being supported by pandas, the string module in pandas and working with SQL:

1) Pandas

```python
result = (df
          .query('A == "foo"')
          .groupby('B')
          .mean()
          .sort_values(by='C'))
```

2) String module in python
```python
s = "   HELLO, WoRLD!   "

result = s.strip().lower().replace('world', 'everyone')
```

3) SQL (alchemy):

```python
    stmt = (
        select(Address)
            .join(Address.user)
            .where(User.name == "sandy")
            .where(Address.email_address == "sandy@sqlalchemy.org")
    )
```

What do you think? Do you think this would be easier for users? More complicated? Even if we don't adopt this workflow I think it is useful to discuss it as an alternative design decision or at least to reveal in an structured manner why our preferences are different.

**Comment by CodyCBakerPhD** [comment]
Also comes up on discussion chain https://github.com/catalystneuro/neuroconv/pull/455#discussion_r1224448221

**Comment by bendichter** [comment]
I like method chaining in general, but I don't know if it is the best approach here. This use-case feels different from the examples, though I can't quite put my finger on why. I'll keep thinking about it.

**Comment by bendichter** [comment]
@h-mayorquin ok I figured out how this is different from your examples. In each of your examples, the desired output class is the class that contains the method. With Pandas, the `DataFrame` has the methods, and the desired output is a `DataFrame`. With Python `str`, the `str` class has the methods and the desired output is a `str`. The same is true for SQLAlchemy, where the output is presumably some kind of query object. For us, to get around the complexity of bounded vs. unbounded `NWBFile` objects, let's say the desired output is an in memory `NWBFile`, so for us to benefit from the elegance of method chaining here, you would need `NWBFile` to contain the method, so the syntax would be:

```python
(
    nwbfile = create_nwbfile_from_metadata(metadata)
        .add_interface(interface1)
        .add_interface(interface2)
        .add_interface(interface3)
)
with NWBHDF5IO(fpath, "w") as io:
    io.write()
```

This seems to me the only way that method chaining would have the same elegance here as it does in the examples. However, I don't think we should do it this way for a few reasons. This would require that we add support for NeuroConv within PyNWB and it is beyond the scope of PyNWB to handle automated conversions This would deviate quite a bit from our current pattern, where interfaces are combined into converters. The current pattern allows for much more control over how interfaces are combined together and how metadata is added. You would use the extract-modify-use pattern from metadata, and without that it's unclear how you would manage required metadata that is missing

**Comment by h-mayorquin** [comment]
Hi, @bendichter 

> This would require that we add support for NeuroConv within PyNWB and it is beyond the scope of PyNWB to handle automated conversions

Does it? I was thinking that a simple wrapper could do the job:

```python
class NWBWrapper(NWBFile):
    
    def __init__(self, metadata):
        nwbfile_kwargs = make_nwbfile_kwargs_from_metadata(metadata)
        super().__init__(**nwbfile_kwargs)
        self.data_interfaces_dict = dict()
           
    def add_data_interface(self, data_interface: BaseDataInterface) -> "NWBWrapper":
        
        data_interface.add_to_nwbfile(self)
        
        name = "some_unque_name_like_in_the_pipeline" # Logic for naming
        self.data_interfaces_dict[name] = data_interface
    
    def write(self, nwbfile_path: str):
        # Validations
        # Configure datasete using the data interfaces methods
        # Write the nwbfile
    
    def make_nwbfile_kwargs_from_metadata(self, metadata) -> dict:
        
        # This is just the `make_nwbfile_from_metadata`` without the initialization at the end
        # And returns the nwbfile_kwargs instead of the nwbfile
       
        return nwbfile_kwargs
```

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
Concerning your counter-example:
```python
 nwbfile_conversor = nwb_conversor(metadata)  # This can work as an initializer for an nwb-file in memory with basic metadata
nwbfile_conversor.add_interface(interface1)
nwbfile_conversor.add_interface(interface2)
nwbfile_conversor.write()  # <- writing / bounding / compression happens here
nwbfile_conversor.add_interface(interface3)  # operation is still possible, but what does this mean in the context of post-write?
nwbfile_conversor.write()  # operate in append mode? That can get tricky. Does it skip the earlier interfaces? 
```

Seems straighforward to me, it should write a file to disk and keep the in memory file in the current state (like `pd.to_csv`). So in the context of post-write you keep adding files to the in-memory. If you write again with the same name you ovewrite or your throw an error. I don't see the need to support append mode. 

What are downsides or errors with this view? I am sticking to what other writing operations in method chaining do.

**Comment by CodyCBakerPhD** [comment]
> Seems straighforward to me, it should write a file to disk and keep the in memory file in the current state (like pd.to_csv). So in the context of post-write you keep adding files to the in-memory. If you write again with the same name you ovewrite or your throw an error. I don't see the need to support append mode.

```python
nwbfile_conversor = nwb_conversor(metadata) 
nwbfile_conversor.add_interface(interface1)  # Big dataset, takes several hours
nwbfile_conversor.write() 
nwbfile_conversor.add_interface(interface2) # Also a big dataset, would take several hours
nwbfile_conversor.write() # If error, then big whoops. Wasted a lot of time to realize the correct workflow
# If overwrite, then new file wouldn't have interface1. Also wasted time
```

Overall the biggest downside is user confusion about the workflow, which is why our current `source_data` (NWBConverter) and `data_interfaces` (ConverterPipe) approaches both limit the dynamic inclusion or exclusion of interfaces at time of initialization.

Other sources of confusion could include but are not limited to

```python
nwbfile_conversor = nwb_conversor(metadata) 
nwbfile_conversor.add_interface(interface1) 
new_metadata = nwbfile_conversor.get_metadata() # contains metadata extracted from interface 1
# but might not even be valid for calling the final `write` on
nwbfile_conversor.add_interface(interface2)
newer_metadata = nwbfile_conversor.get_metadata() 
# I'd need to keep re-fetching this each time to see what's different?
merged_metadata = deep_dict_update(new_metadata, newer_metadata)
# What if I make manual modifications at some point?
# How do I ensure those don't get overwritten during deep_dict_update?
# Really, manual modifications would only be introduced immediately before `write`
# but there's no way to enforce that with this workflow
nwbfile_conversor.write(metadata=merged_metadata)
```

Also two more of my cents; all-in-all, the future recommendation for maximum ease of use is going to be to use the NWB GUIDE (you should give it a quick try BTW, we have a built-in tutorial now that relies on the GIN ephy testing data - will have a step-by-step documentation for it soon - you may encounter some errors with ecephys metadata until Garrett gets back next week and we push some fixes), in which case the NeuroConv API will largely exist to facilitate the endpoints used over there, so we really don't need to reinvent the NeuroConv API for better convenience when a far better solution like that is already in the works

**Comment by CodyCBakerPhD** [comment]
> Was this done intentionally?

Yes, it acts on the `nwbfile` input argument in-place

> Would there be any downsides to return the in-memory modified nwbfile instead?

Same difference, nothing gained. Unless you start talking about creating a copy of an in-memory NWBFile object (i.e., not yet written to disk), which does not sound fun to implement (how to deal with unwritten datasets across copies? What if one copy is written to disk before the other? So many conditions to think about...), and also then it would become more inefficient if using syntax like `nwbfile = interface1.add_to_nwbfile(nwbfile)` because even if you were properly copying and whatnot, you'd be deleting the input object and replacing with a fresh copy plus new additions each time you replace the reference in the local namespace

**Comment by CodyCBakerPhD** [comment]
> Is there possible that any add method will take several hours? 

It's not the add method, it's the write the immediately follows it. Sorry if placement of comments confused


> I think that I am missing from your example the nature of your error. It is just that th error appears when you add or write the second interface? There is no reason for you to have two writes. You put a write if you want to see if the current thing works and then remove it. Maybe there is something I am missing?

Case 1 is throwing the error you suggest in

> If you write again with the same name you ovewrite **or your throw an error**. I don't see the need to support append mode.

That is, we specifically prevent people from being able to call `write` a second time on the same 'wrapped' file as you suggest


> There is no reason for you to have two writes. You put a write if you want to see if the current thing works and then remove it. 

Sure there is, such as backing up progress in an iterative fashion. Or just generally interacting with these objects in a long notebook interspersed with other analyses/operations. Just basing off of what we've seen from researchers after all these years; if you make the workflow interactive, every possibility that is enabled will eventually be attempted

This is currently supported with `run_conversion` workflow by leveraging append mode; but it has a different call signature, and requires separate instantiation of what is most likely a different NWBConverter object altogether (even if writing to same file on disk)

**Comment by CodyCBakerPhD** [comment]
> I find the first more expressive of intent for myself, do you dislike this or think that is misleading in some way?

I see zero difference personally, aside from the mild annoyance that the return observed in `nwbfile = interface.add_to_nwbfile(nwbfile=nwbfile)` is technically meaningless (redefining a fresh local reference to a pointer)

Perhaps first time programmers might be thrown, if they are accustomed to classic functional input-output patterns and have not yet been exposed to pass by reference. So there is something to be said there, BUT I still think those users should be using the GUIDE not NeuroConv, as per above comment about the future of maximum user-friendliness 😉

**Comment by h-mayorquin** [comment]
If using this type of code will be relegated to power users and you envision that most users without experience will use the GUIDE that we should care less about guardrails. 

I am fine with power users spending more time because they wrote a `write` argument twice in the middle of a pipeline if this enables a more interactive and iterative use of the code when you are building. 

Like, torch, pandas and scikit-learn that do heavy operations do not shield you from accidentally running some long training, to_csv or fit operation.

That said, that is a clear reason for why we do it this way and I understand it and can roll with it.

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
> I see zero difference personally, aside from the mild annoyance that the return observed in nwbfile = interface.add_to_nwbfile(nwbfile=nwbfile) is technically meaningless (redefining a fresh local reference to a pointer)

OK. Technically meaningless but quite common in the scientific stack.

> Perhaps first time programmers might be thrown, if they are accustomed to classic functional input-output patterns and have not yet been exposed to pass by reference. So there is something to be said there, BUT I still think those users should be using the GUIDE not NeuroConv, as per above comment about the future of maximum user-friendliness

It is not first time programers that are acustomed to this. This is a preference from fluent interfaces. Check out numpy out argument in ufunction or how people write pandas code even when using inplace.

**Comment by bendichter** [comment]
In standard python, methods that update a mutable object in place generally do not output that object. For example, `dict.update()` updates a `dict` in place and does not output the new `dict`. `list.append()` similarly updates the mutable `list` object in place and does not output the new `list`.

**Comment by h-mayorquin** [comment]
This is true. Thinking about it, the only part of the standard library that works with method chaining is the string module. 

The function sorted that operatores on a list does return a list though. But the method does not as you pointed out.

**Comment by h-mayorquin** [comment]
OK, guys, I enjoyed discussing this with you.

I think that you pointed out difficulties that will come from this decision mainly but not exhaustively:
* I will require some extra code here in the best case scenario or in pynwb in the worst case scenario as @bendichter pointed out.
* @CodyCBakerPhD also pointed out how some faulty workflows can become more likely if we were to support this.

Those are costs. I can argue about the magnitude of those costs but what I am failing to provide is clear benefits of supporting method chaining that will clearly make the costs worth it. So far, I don't think those are very clear. So, even if I still like these types of APIs I have to put my engineer and reject this as our efforts are probably better spent somewhere else as @CodyCBakerPhD pointed out.

Feel free to close this. I am wondering whether this type of discussion is better carried out in something like https://docs.github.com/en/discussions/quickstart but I also don't like fragmenting the sources.
