### ISSUE TITLE
Rename add_* tool functions

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#474]
_Originally posted by @h-mayorquin in https://github.com/catalystneuro/neuroconv/pull/455#discussion_r1224233143_

> I think it would be nice if all the other names in the tools followed the convention of `to_nwb`. Right now, they are `add_recorder`, `add_sorting` instead of `add_recorder_to_nwb`
          
So to clarify, we want all the helper functions under `tools` to follow the convention `add_{native API object/class type}_to_nwb`

E.g., what is currently `add_sorting` in `tools.spikeinterface` should become `add_sorting_to_nwb`

Should this also apply to the `write_*` methods? E.g., `write_sorting` -> `write_sorting_to_nwb`?

**Comment by h-mayorquin** [comment]
Making everything both consistent and explicit seems like the way to go to me. My vote is for that.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin But what's the boundary on 'explicit'? Should it be the full snake case of the native API object class, e.g., `add_recording_extractor_to_nwb`?

**Comment by CodyCBakerPhD** [comment]
to differentiate `add_neo_rawio_to_nwb` from `add_neo_extractor_to_nwb` (not that we would ever have that; even if we did they would be in different submodules; just asking w.r.t consistency)

**Comment by h-mayorquin** [comment]
Yeah, that would be fine to me. Most people feel umcomfortable with that much verbosity but I don't. I am more concern with the consistency in the suffix to fully indicate the action that with the part of the name that characterize the object being added.
