### ISSUE TITLE
[Documentation] MovieInterface text is misaligned in the documentation

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#5]
Check the latest built by the docs:
https://nwb-conversion-tools.readthedocs.io/en/main/api/interfaces.behavior.html#nwb_conversion_tools.datainterfaces.behavior.movie.moviedatainterface.MovieInterface

The documentation seems to stick out out to the whie space. 

![Screenshot from 2022-07-21 17-37-31](https://user-images.githubusercontent.com/6429509/180254702-c6e68d1b-7001-4416-a324-e7385d0005e5.png)

**Comment by h-mayorquin** [comment]
Great!

**Comment by CodyCBakerPhD** [comment]
(I'm assuming the PyData transition fixed things - if not please reopen and try to find other occurrences)

**Comment by h-mayorquin** [comment]
I did go and check, I will open other issue if I find more things like that.
