### ISSUE TITLE
[Documentation]: Remove old tutorials and their interfaces

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#50]
### What would you like changed or added to the documentation and why?

All NeuroConv interfaces should operate on files that are on the users disk, and all tutorials should harness our example data from GIN to make this happen (though preferably try it out on their own data as well).

Thus the old tutorials here: https://github.com/catalystneuro/neuroconv/tree/main/tutorials

should be removed as well as their interfaces: https://github.com/catalystneuro/neuroconv/tree/main/src/neuroconv/datainterfaces/ecephys/tutorial

which are built on synthetic in-memory SpikeInterface objects.

To replace these, some recent tutorials (including of the `.yml` feature) were put together for the user days here: https://github.com/NeurodataWithoutBorders/nwb_hackathons/tree/main/HCK13_2022_Janelia/projects/neuroconv_tutorial

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by h-mayorquin** [comment]
I am concerned about gin being difficult to install for some people. Tutorials working with synthetic data do not have that dependency problem.

What's the problem with having the two of them available?

**Comment by CodyCBakerPhD** [comment]
I had people download two files manually from GIN, which was easy enough. The tutorial doesn't have to harness the entire GIN dataset.

It's also recommended to use the DANDIHub for all of it anyway, where data is already available.
