### ISSUE TITLE
[Bug]: Converting MaxOne omits data?

### ISSUE THREAD

**Issue by DailyDreaming** [catalystneuro/neuroconv#553]
### What happened?

I've converted a MaxOne / Maxwell ("*.raw.h5") file into NWB Format using neuroconv and it produced data with a different shape (omitting rows)?

```
import h5py

from pynwb import NWBHDF5IO

nwb_filepath = '2023-04-02-e-hc328_unperturbed/original/data/hc3.28_hckcr1_chip16835_plated34.2_rec4.2.nwb'
h5_filepath = '2023-04-02-e-hc328_unperturbed/original/data/hc3.28_hckcr1_chip16835_plated34.2_rec4.2.raw.h5'

with NWBHDF5IO(nwb_filepath, mode='r', load_namespaces=True) as nwb:
    with h5py.File(h5_filepath, 'r') as h5:
        nwbfile = nwb.read()
        nwb_data = nwbfile.acquisition["ElectricalSeries"].data.shape
        h5_data = h5['sig'].shape
        print(f'nwb: {nwb_data}')
        print(f'h5: {h5_data}')
```

Gives me:

```
nwb: (7964800, 972)
h5: (1028, 7964800)
```

I'm not sure I care about the dataframe/dataset seemingly being transposed.  I assume that that's an idiosyncrasy of the format?  But it looks like it just dropped 28 + 28 rows?

### Steps to Reproduce

Convert a MaxOne / Maxwell ("*.raw.h5") file to NWB format and then check the shape of the resulting `ElectricalSeries` data.

I used this script to convert:

```python
import os
from datetime import datetime
from dateutil import tz
from pathlib import Path
from neuroconv.datainterfaces import MaxOneRecordingInterface

file_path = '/home/ubuntu/2023-04-02-e-hc328_unperturbed/original/data/hc3.28_hckcr1_chip16835_plated34.2_rec4.2.raw.h5'
interface = MaxOneRecordingInterface(file_path=file_path, verbose=True)

metadata = interface.get_metadata()
print(metadata)
# 2023-04-02T13:45:23
session_start_time = datetime(2023, 4, 2, 13, 45, 23, tzinfo=tz.gettz("US/Pacific"))
metadata["NWBFile"].update(session_start_time=session_start_time)

# Choose a path for saving the nwb file and run the conversion
nwbfile_path = '2023-04-02-e-hc328_unperturbed/original/data/hc3.28_hckcr1_chip16835_plated34.2_rec4.2.nwb'
interface.run_conversion(nwbfile_path=nwbfile_path, metadata=metadata)
```

### Traceback

No traceback.

### Operating System

Linux

### Python Executable

Python

### Python Version

3.10

### Package Versions

<details>

aiohttp==3.8.5
aiosignal==1.3.1
appdirs==1.4.4
asciitree==0.3.3
asttokens==2.2.1
async-timeout==4.0.3
attrs==21.2.0
Automat==20.2.0
awscli==1.22.34
Babel==2.8.0
backcall==0.2.0
bcrypt==3.2.0
bidsschematools==0.7.1
blessed==1.20.0
blinker==1.4
boto3==1.28.29
botocore==1.31.29
bqplot==0.12.40
certifi==2020.6.20
chardet==4.0.0
charset-normalizer==3.2.0
ci-info==0.3.0
click==8.1.7
click-didyoumean==0.3.0
cloud-init==23.2.2
colorama==0.4.4
comm==0.1.4
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
contourpy==1.1.0
cryptography==3.4.8
cycler==0.11.0
dandi==0.56.0
dandischema==0.8.4
dbus-python==1.2.18
decorator==5.1.1
distlib==0.3.4
distro==1.7.0
distro-info==1.1+ubuntu0.1
dnspython==2.4.2
docutils==0.17.1
ec2-hibinit-agent==1.0.0
email-validator==2.0.0.post2
entrypoints==0.4
etelemetry==0.3.0
executing==1.2.0
fasteners==0.18
filelock==3.6.0
fonttools==4.42.1
fparse==1.20.1
frozenlist==1.4.0
fscacher==0.4.0
fsspec==2023.6.0
gast==0.4.0
gyp==0.1
h5py==3.9.0
hdmf==3.8.1
hibagent==1.0.1
httplib2==0.20.2
humanize==4.8.0
hyperlink==21.0.0
idna==3.3
imageio==2.31.1
importlib-metadata==4.6.4
incremental==21.3.0
interleave==0.2.1
ipydatagrid==1.1.16
ipydatawidgets==4.3.2
ipyfilechooser==0.6.0
ipympl==0.9.3
ipython==8.14.0
ipython-genutils==0.2.0
ipyvolume==0.6.3
ipyvue==1.9.2
ipyvuetify==1.8.10
ipywebrtc==0.6.0
ipywidgets==8.1.0
isodate==0.6.1
jaraco.classes==3.3.0
jedi==0.19.0
jeepney==0.7.1
Jinja2==3.0.3
jmespath==0.10.0
joblib==1.3.2
jsonpatch==1.32
jsonpointer==2.0
jsonschema==3.2.0
jupyterlab-widgets==3.0.8
keyring==23.5.0
keyrings.alt==5.0.0
kiwisolver==1.4.4
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy_loader==0.3
MarkupSafe==2.0.1
matplotlib==3.7.2
matplotlib-inline==0.1.6
more-itertools==8.10.0
multidict==6.0.4
natsort==8.4.0
ndx-grayscalevolume==0.0.2
ndx-icephys-meta==0.1.0
ndx-spectrum==0.2.2
neo==0.12.0
netifaces==0.11.0
networkx==3.1
neuroconv==0.4.1
numcodecs==0.11.0
numpy==1.25.2
nwbinspector==0.4.29
nwbwidgets==0.11.3
oauthlib==3.2.0
olefile==0.46
packaging==21.3
pandas==2.0.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
platformdirs==2.5.1
plotly==5.13.1
probeinterface==0.2.17
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
py2vega==0.6.1
pyasn1==0.4.8
pyasn1-modules==0.2.1
pycryptodomex==3.18.0
pydantic==1.10.12
Pygments==2.11.2
PyGObject==3.42.1
PyHamcrest==2.0.2
PyJWT==2.3.0
pynwb==2.4.0
pyopenephys==1.1.6
pyOpenSSL==21.0.0
pyout==0.7.3
pyparsing==2.4.7
pyrsistent==0.18.1
pyserial==3.5
python-apt==2.4.0+ubuntu2
python-dateutil==2.8.2
python-debian==0.1.43+ubuntu1.1
python-magic==0.4.24
pythreejs==2.4.2
pytz==2022.1
PyWavelets==1.4.1
PyYAML==5.4.1
quantities==0.14.1
requests==2.25.1
rfc3987==1.3.8
roman==3.3
rsa==4.8
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3transfer==0.6.2
scikit-image==0.21.0
scipy==1.11.1
SecretStorage==3.3.1
semantic-version==2.10.0
service-identity==18.1.0
six==1.16.0
sos==4.4
spikeinterface==0.98.2
ssh-import-id==5.11
stack-data==0.6.2
strict-rfc3339==0.7
systemd-python==234
tenacity==8.2.3
threadpoolctl==3.2.0
tifffile==2023.8.12
tqdm==4.66.1
traitlets==5.9.0
traittypes==0.2.1
trimesh==3.23.3
Twisted==22.1.0
typing_extensions==4.7.1
tzdata==2023.3
ubuntu-advantage-tools==8001
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.5
virtualenv==20.13.0+ds
wadllib==1.3.6
wcwidth==0.2.6
webcolors==1.13
widgetsnbextension==4.0.8
xmltodict==0.13.0
yarl==1.9.2
zarr==2.16.0
zarr-checksum==0.2.9
zipp==1.0.0
zope.interface==5.4.0

</details>

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Can you describe the probe structure that you're using? The columns in NWB are 'channels', and the reader we use for Maxwell (SpikeInterface/neo) will automatically limit to only use the neural channels (not aux/digital/etc. which would be a separate interface, which we have not developed and would need example data for)

**Comment by DailyDreaming** [comment]
@CodyCBakerPhD Thank you!  Hmmm... so looking further into this, the "mapping" section of the original ".raw.h5" file, has only 972 electrodes described.  Sorry, I'm new to this.  It probably limited the number of channels based on that.  I'll ask the original experimenters about the probe structure used and if this is normal.  I am still curious why 1028 channels of information were included though.  This seems like a discrepancy in the source file.

Thanks again.  Will follow up with more information when I get a reply.

**Comment by CodyCBakerPhD** [comment]
@DailyDreaming Any update from the experimenters? I'm always curious to here such details for formats like this

**Comment by CodyCBakerPhD** [comment]
@DailyDreaming Any more information on if this is a bug on our side, or intended from the source data?

If the second one, can we consider this issue closed?

**Comment by CodyCBakerPhD** [comment]
Closing due to no response

Please open a new issue when/if you get more details regarding the source data discrepancies
