### ISSUE TITLE
[New Format]: multi-probe SpikeGLX

### ISSUE THREAD

**Issue by parviz-gh** [catalystneuro/neuroconv#562]
### What format would you like to see added to NeuroConv?

hello , it would be great to  add multi-shank/probe raw data selection (like lf or ap files that are generated by SpikGlx ) in nwb-guide.

### Does the format have any documentation?

No, as far as I know 

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Hi!

If this request is specific to the NWB GUIDE, could you open it on that repo so it can be tracked?

https://github.com/NeurodataWithoutBorders/nwb-guide/issues/new/choose

As far as NeuroConv goes, the easiest thing for SpikeGLX is the `SpikeGLXConverter`

Instructions on how to use that class can be found here (can handle multiple probes, theoretically multiple gates as well - there are some planned improvements to metadata representation but the data itself should all make its way into the NWB file): https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/recording/spikeglx.html

**Comment by CodyCBakerPhD** [comment]
Ah, but I see https://github.com/NeurodataWithoutBorders/nwb-guide/issues/356 has already been raised, strange I didn't receive notification of that one until I checked

**Comment by CodyCBakerPhD** [comment]
@parviz-gh Have you had a chance to check out the `SpikeGLXConverter` yet? It should be capable of doing what you're requesting in this issue

**Comment by parviz-gh** [comment]
@CodyCBakerPhD . Yes , I tried it . It works for single stream (one probe ). As far as I undrestood , all the functions aceept address of one stream NOT list of streams .

**Comment by CodyCBakerPhD** [comment]
This was finally solved recently by #957
