### ISSUE TITLE
[Bug]: "IndexError: list index out of range" when converting plexon files

### ISSUE THREAD

**Issue by CHEN-CR-JS** [catalystneuro/neuroconv#566]
### What happened?

When converting the .plx file, an error "list index out of range" pops out. 

OS: Windows11 22H2
Visual Studio Code
Python 3.11.4

### Steps to Reproduce

```python
>>> interface = PlexonRecordingInterface(file_path=file_path, verbose=False)
```

### Traceback

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\anaconda\Lib\site-packages\neuroconv\datainterfaces\ecephys\plexon\plexondatainterface.py", line 25, in __init__
    super().__init__(file_path=file_path, verbose=verbose, es_key=es_key)
  File "C:\anaconda\Lib\site-packages\neuroconv\datainterfaces\ecephys\baserecordingextractorinterface.py", line 32, in __init__
    self.recording_extractor = self.get_extractor()(**source_data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda\Lib\site-packages\spikeinterface\extractors\neoextractors\plexon.py", line 32, in __init__
    NeoBaseRecordingExtractor.__init__(
  File "C:\anaconda\Lib\site-packages\spikeinterface\extractors\neoextractors\neobaseextractor.py", line 210, in __init__
    stream_id = stream_ids[0]
                ~~~~~~~~~~^^^
IndexError: list index out of range
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.7

### Package Versions

[environment_for_issue.txt](https://github.com/catalystneuro/neuroconv/files/12623169/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
By the looks of it, this means to streams were found in the `.plx` file (at least via the current IO readers)

Would you be willing to share your example data (dropbox/drive/etc)? That would rapidly speed up the debugging process.

**Comment by CHEN-CR-JS** [comment]
https://drive.google.com/file/d/1w9YXOXIhgvy4ek1NkF5QQ6HYAJEzDqAc/view?usp=drive_link

**Comment by CHEN-CR-JS** [comment]
Sure, I'll make a new sample file later this night. What would be an appropriate email to share it with?

**Comment by CodyCBakerPhD** [comment]
Actually, it looks like the simplest explanation for this is that the `.plx` file you are pointing to does not contain any recording streams, but instead only  has spike sorting

If that's the case, then you just need to use the appropriate interface and the streams will be found

```python
# recording_interface = PlexonRecordingInterface(file_path=file_path, verbose=False)
# Error: no recording streams found

sorting_interface = PlexonSortingInterface(file_path=file_path, verbose=False)
# Should load fine now
```

**Comment by CHEN-CR-JS** [comment]
It works! Thank You!

**Comment by CodyCBakerPhD** [comment]
Great, just let us know if you run into any other issues

Cheers ~

**Comment by CHEN-CR-JS** [comment]
@CodyCBakerPhD Do you know how to make the NeuroConv converts all streams of an unsorted plexon file by default?

**Comment by CodyCBakerPhD** [comment]
> Do you know how to make the NeuroConv converts all streams of an unsorted plexon file by default?

We did this for the SpikeGLXConverter (finds and converts all streams available) but have not yet made one for Plexon, largely because we just haven't seen an example of multi-stream Plexon recordings/sortings just yet - we would need this to add testing infrastructure around it

So if you have a small snippet you could share over Google Drive, the email is CodyCBakerPhD@gmail.com

**Comment by CHEN-CR-JS** [comment]
Thanks for the response. I try to make a sample tomorrow.
