### ISSUE TITLE
Choosing an interface to store in NWB file

### ISSUE THREAD

**Issue by MKVarun** [catalystneuro/neuroconv#572]
I was wondering if there's a way to choose an interface class to store in NWB if I have several interface classes (OpenEphys, PhySorting, KiloSortSorting).

**Comment by CodyCBakerPhD** [comment]
When you have multiple data streams to put into a single NWB file, you can easily choose which interfaces to combine in NeuroConv as shown in our galleries for combining interfaces, such as this one for SpikeGLX (NeuroPixels) + Phy

https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/combinations/spikeglx_and_phy.html

**Comment by MKVarun** [comment]
So I actually created the interface this way (as in the documentation):

```
class ExampleNWBConverter(NWBConverter):
    data_interface_classes = dict(
        SpikeGLXRecording=SpikeGLXRecordingInterface,
        PhySorting=PhySortingInterface
    )
source_data = dict(
    SpikeGLXRecording=dict(
        file_path="raw_dataset_path"
    ),
    PhySorting=dict(
        folder_path="sorted_dataset_path"
    )
)

example_nwb_converter = ExampleNWBConverter(source_data)
```

But I wanted to select only one of the interfaces while converting to NWB, say PhySorting only.

**Comment by CodyCBakerPhD** [comment]
Turns out, that's even easier!

Just don't include the interface in the `source_data` dictionary

All classes defined in the `data_interface_classes` are optional and only instantiated if defined by the `source_data` entries

**Comment by CodyCBakerPhD** [comment]
@MKVarun Any luck getting this to work on your end?

I guess my big TODO from this issue would be to enhance the documentation to make this feature more apparent

**Comment by MKVarun** [comment]
Yes, one of the solutions you provided works for me. 

My idea was to read metadata across the two folders (Spike and Phy) and then provide an option for users to include one or both of the folders, instead of having to create an interface again and repeat reading folders. 

For example, in my dataset, the metadata is stored in the Spike folders and I wanted to create NWB files with Phy data. What I am currently doing is create a converter for Spike and Phy folders get the metadata across the folders, create a converter for Phy/Spike and use the metadata extracted in the first case to create NWB files. However, this requires two Interface calls. It would be faster if I could call the Interface function on both folders at once, get the metadata across folders and then allow my user option to choose which of the two folders' data to include.

**Comment by h-mayorquin** [comment]
Also, you can do this by just commenting out one line if you usa a `ConverterPipe` object like the one described here:

https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/combinations/spikeglx_and_phy.html

There, data_interfaces is a list that you can enhance and drop programatically as you wanted.


There are two solutions for this issue, are you guys fine with closing it?

**Comment by h-mayorquin** [comment]
OK, a month went by. I will close this issue. Feel free to open a new one if that is needed.
