### ISSUE TITLE
[Question]: Assigning two `PhotonSeries` to the same `ImagingPlane` 

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#575]
The metadata for the `TwoPhotonSeries` and the `ImagingPlane` are lists (as we can have more than one).

Example from the current Clandinin conversion:
```
metadata["Ophys"]["TwoPhotonSeries"]
[{'name': 'FunctionalGreenTwoPhotonSeries', 'description': 'Imaging data acquire...ng readout', 'unit': 'px', 'imaging_plane': 'ImagingPlane', 'dimension': [...], 'format': '.nii', 'scan_line_rate': 15833.056254848874, 'field_of_view': [...]}, {'name': 'FunctionalRedTwoPhotonSeries', 'description': 'Imaging data acquire...istration.', 'unit': 'px', 'imaging_plane': 'ImagingPlane', 'dimension': [...], 'format': '.nii', 'scan_line_rate': 15833.056254848874, 'field_of_view': [...]}]
len(metadata["Ophys"]["TwoPhotonSeries"])
2
```

When writing a conversion with multiple interfaces we use the conversion options in `BaseImagingExtractorInterface` to specify which metadata belongs to a specific interface:

https://github.com/catalystneuro/neuroconv/blob/6164f98c8d271c5432cc45d4c5c745b15721060c/src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py#L101-L109

The argument is called `photon_series_index` and is used here:

https://github.com/catalystneuro/neuroconv/blob/6164f98c8d271c5432cc45d4c5c745b15721060c/src/neuroconv/tools/roiextractors/roiextractors.py#L355-L356

To my surprise, I realized that the the same index is used to determine which metadata is used to build the corresponding `image_plane_index`:

https://github.com/catalystneuro/neuroconv/blob/6164f98c8d271c5432cc45d4c5c745b15721060c/src/neuroconv/tools/roiextractors/roiextractors.py#L364-L365

Which, if I understand well, means that if I want to assign TwoPhotonSeries to the same imaging series I need to duplicated my metadata.

---

Maybe this work as intended and each `TwoPhotonSeries` should have ony `ImagingPlane` assigned? I think this is the decision that we did for Brucker.

I think this all comes from my confusion about the intent behind the `ImagingPlane`. When I first heard about volumetric data I was expecting that that would need multiple ImagingPlanes, one for every dimension of depth but this turned out to be false. On the other hand, I kind of expected that for formats with multiple channels (like Brucker) we could save one imagine plane with two `TwoPhotonSeries` referencing it and each `TwoPhotonSeries` somehow linked to their respective `OpticalChannel`. However, it seems that there is no way of doing this, as there is no way to directly link `OpticalChannel` back to the `TwoPhotonSeries`...

This is strange because `OpticalChannel` as an argument of `ImagingPlane` has a list type which I thought was meant to be used for ImagingPlanes with multiple channels but then how to disambiguate which series belongs to which channels? `TwoPhotonSeries` can only store one channel, either images or volumetric but not multiple channels.

**Comment by weiglszonja** [comment]
@h-mayorquin Propagating the `imaging_plane_index` in` add_imaging_plane()` to the `add_photon_series` you're right is not an ideal solution, this is why the TODO was added there to eventually change this:
https://github.com/catalystneuro/neuroconv/blob/6164f98c8d271c5432cc45d4c5c745b15721060c/src/neuroconv/tools/roiextractors/roiextractors.py#L363-L365

So basically `add_imaging_plane` would instead have `"photon_series_key"` where you can specify the name of the photon series you want to add the imaging plane for. 

I have a different example that we can think about; for the Pinto lab we have the raw and the motion corrected `OnePhotonSeries` data. I would use the same imaging plane, but currently as you noticed it could only be done if I would duplicate the metadata. I'm not sure in that case having a `"photon_series_key"` would solve the problem.

**Comment by CodyCBakerPhD** [comment]
> It is also confusing for me that the indicator is in the ImagingPlane but that the emission_lambda is a property of the optical channel.

Another great point that @alessandratrapani can add to their ongoing list of improvements to implement to our ophys modalities 😃

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Can this issue be closed? It's technically possible as @weiglszonja pointed out, even if not that ideal of a design (but that improvement is already a part of some older issues

**Comment by weiglszonja** [comment]
@h-mayorquin @CodyCBakerPhD Now to think of it, how would you feel about changing `imaging_plane_index` to `imaging_plane_name`? `add_imaging_plane` is used in segmentation as well, 
https://github.com/catalystneuro/neuroconv/blob/44397a8626567c12b9d624fcafa7aa23d62638c6/src/neuroconv/tools/roiextractors/roiextractors.py#L690
so "photon_series_key" might be misleading there. 
(I started drafting for #581 and realised if I wanted to test if we have raw and processed (e.g. downsampled) two photon series data that we add to acquisition and processing it could only be done by duplicating the metadata as @h-mayorquin pointed out)

**Comment by CodyCBakerPhD** [comment]
Yes, the plan is always to swap from indexing of a list to string key identifier of a dictionary
