### ISSUE TITLE
[Proposal] Use `ZoneInfo` instead of `dateutil` for time zone specification

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#599]
Since python 3.9 zoneinfo has been accepted as the standard way of handling time zones and has been included in the standard library:
https://docs.python.org/3/library/zoneinfo.html

However, in the gallery and in some conversions were are still using dateutil for this (example):

https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/recording/openephys.html

We still are supporting python 3.8 so we can not just use `ZoneInfo` as it is. Fortunately, there is a backport for this specific purpose:|
https://pypi.org/project/backports.zoneinfo/

Which we can use that right now to start using the standard solution and avoid the installation of an extra dependency for users that use python 3.9.

**Comment by CodyCBakerPhD** [comment]
This would be an easier kind of thing to fix if we had a helper/util function for adding timezone info to a datetime; something that would also reduce the number of top level imports and raw number of lines across each gallery snippet

**Comment by h-mayorquin** [comment]
Maybe the easier thing is to wait till we can drop support for python 3.8 which will be in a year (2024-10-01).

https://devguide.python.org/versions/ 

But point in favor to  @CodyCBakerPhD previous proposal to have util functions for setting timing information. This  would avoid this problem.
