### ISSUE TITLE
Update remaining RecordingInterfaces to use SpikeInterface backend

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#60]
- [x] IntanRecordingInterface
- [x] BlackrockRecordingExtractorInterface
- [x] BlackrockSortingExtractorInterface 
- [x] CED [Not tested in the old backend]
- [x] Cell Explorer [Not available in spikeinterface]
- [x] Neuralynx 
- [x] NeuroscopeSortingExtractor
- [x] OpenEphys
- [x] PhySortingInterface
- [x] SpikeGadgetsRecordingInterface
- [x] Axona
- [x] Axona LFP

@h-mayorquin Please add the others, thanks! (Done!)

**Comment by h-mayorquin** [comment]
Axona has been added to spikeinterface:
https://github.com/SpikeInterface/spikeinterface/pull/529
