### ISSUE TITLE
[Documentation]: Possible mistake: pip install -e . neuroconv[test,full]

### ISSUE THREAD

**Issue by magland** [catalystneuro/neuroconv#642]
### What would you like changed or added to the documentation and why?

In https://github.com/catalystneuro/neuroconv/blob/main/docs/developer_guide/testing_suite.rst

I read

> Then install all required and optional dependencies in a fresh environment.
> pip install -e . neuroconv[test,full]

But maybe you mean

`pip install -e .[test,full]`

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Yep, good catch!
