### ISSUE TITLE
[Backend Follow-up]: Change 'location' field name to 'location_in_file'

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#660]
### What would you like to see added to NeuroConv?

To avoid confusion with 'location' as interpreted as 'brain area' in NWB

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
Great. Thanks for following up on this.
