### ISSUE TITLE
Suite2pSegmentationInterface sampling rate not changing.

### ISSUE THREAD

**Issue by msoheib** [catalystneuro/neuroconv#690]
Hello!

I am building on the example code from the docs to add my suite2p segmentation data and traces to nwb file format. Thank you for making this.

I have a total of 12799 frames that were processed so my F.npy file is 520x 12799.
![nwb](https://github.com/catalystneuro/neuroconv/assets/95087523/073acdc5-27ac-4b3f-8439-a6bf3dadec96)

The code below runs without errors, but the roi response tracing has been converted to seconds using 10 Hz of sampling, as when inspected via nwbwidgets, the time index in seconds ranges from 0.00 to 1279.9 seconds.

To fix this I have tried to update the metadata before conversion, but still, the new output is the same. Based on the documentation, I am not sure if I am missing something and would appreciate any direction in this regard.

Thank you.

```

#%%
from datetime import datetime
from dateutil import tz
from pathlib import Path
from neuroconv.datainterfaces import Suite2pSegmentationInterface
from neuroconv.tools.roiextractors import roiextractors
folder_path= r"\\wt\\suite2p"
interface = Suite2pSegmentationInterface(folder_path=folder_path, verbose=True)

metadata = interface.get_metadata()

# For data provenance we add the time zone information to the conversion
session_start_time = datetime(2020, 1, 1, 12, 30, 0, tzinfo=tz.gettz("US/Pacific"))
metadata["NWBFile"].update(session_start_time=session_start_time)
metadata["Fluorescence"].update(rate=30.0, conversion=1.0)
# Choose a path for saving the nwb file and run the conversion

nwbfile_path = r"\\wt\\suite2p\\output_file.nwb"

#%%
interface.run_conversion(nwbfile_path=nwbfile_path, metadata=metadata)


```

**Comment by CodyCBakerPhD** [comment]
Hi there! Welcome to NeuroConv, and thank you for posting such a well-detailed issue!

I'm sorry it's not made more obvious by the function calls or documentation, but the `rate` field of any `RoiResponseSeries` (of which `Fluorescence` from Suite2P is one) is ignored in the `metadata` - we instead use a separate mechanism to control timing information; the `timestamps` or `sampling_frequency` of the underlying `segmentation_extractor` object

The relevant lines of code can be found here for reference: https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/tools/roiextractors/roiextractors.py#L928-L938

On top of this - we have also recognize in the past that Suite2P is a format that records the sampling frequency of the imaging data that was segmented, and so we extract that automatically in the ROIExtractors package here: https://github.com/catalystneuro/roiextractors/blob/main/src/roiextractors/extractors/suite2p/suite2psegmentationextractor.py#L155

That said, perhaps that option in Suite2P is returning the incorrect value of `10.0` Hz, or that value was set incorrectly from the imaging; the mechanism to override this value in our software would be as follows

```python
from datetime import datetime
from dateutil import tz
from pathlib import Path
from neuroconv.datainterfaces import Suite2pSegmentationInterface
from neuroconv.tools.roiextractors import roiextractors

folder_path= r"\\wt\\suite2p"
interface = Suite2pSegmentationInterface(folder_path=folder_path, verbose=True)

# Correct the sampling frequency
correct_sampling_frequency = 30.0  # in Hz, using 30.0 as an example
interface.segmentation_extractor._sampling_frequency = correct_sampling_frequency 

metadata = interface.get_metadata()

session_start_time = datetime(2020, 1, 1, 12, 30, 0, tzinfo=tz.gettz("US/Pacific"))
metadata["NWBFile"].update(session_start_time=session_start_time)

nwbfile_path = r"\\wt\\suite2p\\output_file.nwb"

interface.run_conversion(nwbfile_path=nwbfile_path, metadata=metadata)
```

I will note that we've been planning for a while now to improve the way time is handled across all of NeuroConv, so this exact way of correcting it should become easier (or at least less hacky...) in the future

**Comment by msoheib** [comment]
Thank you. You are correct the file was looking at the ops file in the suite2p directory and using "fs" value as the sampling frequency. For some reason it was set to default, chnaging that to the correct value seems to give me the correct time axis in the nwb file.

Cheers!
