### ISSUE TITLE
[Bug]: align_by_interpolation introduces duplicate timestamps

### ISSUE THREAD

**Issue by johnmbarrett** [catalystneuro/neuroconv#711]
### What happened?

First off, apologies if this has been discussed before, but I couldn't find any existing issues describing this exact behaviour. Essentially, if the first unaligned timestamp passed to `align_by_interpolation` is after the beginning of the timestamps of the interface being aligned (or the last unaligned timestamp is before the end of the recording), `align_by_interpolation` will introduce duplicate timestamps, since `np.interp` does not extrapolate for query points that are outside the span of the sample points. By duplicate timestamps, I mean multiple samples in the data interface are assigned the same timestamp, i.e. multiple copies of `aligned_timestamps[0]` at the beginning of the recording and multiple copies of `aligned_timestamps[-1]` at the end.

I ran into this when attempting to align two ephys recording systems using a set of regular TTL pulses seen by both systems, so by necessity the first TTL timestamp was after the beginning of the recording. More specifically, I have a Neuropixels system and an Intan recording system, with the former set up (using Open Ephys GUI) to generate a 10 Hz pulse on its SMA line that is connected to one of the analog inputs of the Intan board. However, for simplicity's sake I've included a minimal reproducible example that requires no test data to demonstrate the behaviour.

I'm not sure what the correct behaviour should be in this circumstance, but silently introducing duplicate timestamps seems less than ideal. Other possible options (not all of them necessarily good ideas), off the top of my head:

* Keep the current behaviour but throw a warning
* Throw an error, forcing the user to implement their own alignment logic
* Delete the timestamps (and associated data) outside of the time span of the alignment pulses
* Linearly extrapolate the out-of-sample points using the inferred sample rate

I'm sure there are more that I haven't thought of. In any case, I thought this issue was worth drawing attention to.

### Steps to Reproduce

```python
import numpy as np

from neuroconv import BaseTemporalAlignmentInterface, NWBConverter
from pynwb import NWBFile

class InterpolationTestInterface(BaseTemporalAlignmentInterface):
    def __init__(self, verbose: bool = False, **source_data):
        self.timestamps = self.get_original_timestamps()

        super().__init__(verbose, **source_data)
    
    def get_original_timestamps(self) -> np.ndarray:
        return np.array(range(1000000))/1000.

    def get_timestamps(self) -> np.ndarray:
        return self.timestamps
    
    def set_aligned_timestamps(self, aligned_timestamps: np.ndarray) -> None:
        self.timestamps = aligned_timestamps

    def add_to_nwbfile(self, nwbfile: NWBFile, **conversion_options) -> None:
        pass

class InterpolationTestConverter(NWBConverter):
    data_interface_classes = {'test': InterpolationTestInterface}

    def temporally_align_data_interfaces(self):
        unaligned_timestamps = (100*np.array(range(1,10000)))/1000.
        aligned_timestamps = unaligned_timestamps + 0.0005

        test_interface = self.data_interface_objects['test']
        test_interface.align_by_interpolation(unaligned_timestamps,aligned_timestamps)

source_data = {'test': {}}

converter = InterpolationTestConverter(source_data)
converter.temporally_align_data_interfaces()

interface = converter.data_interface_objects['test']

timestamps = interface.get_timestamps()

assert len(timestamps) == len(np.unique(timestamps))
```

### Traceback

```python
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[4], line 43
     39 interface = converter.data_interface_objects['test']
     41 timestamps = interface.get_timestamps()
---> 43 assert len(timestamps) == len(np.unique(timestamps))

AssertionError:
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.9

### Package Versions

```
# Name                    Version                   Build  Channel
neuroconv                 0.4.7                    pypi_0    pypi
numpy                     1.26.2                   pypi_0    pypi
pynwb                     2.3.1            py39hcbf5309_0    conda-forge
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Thanks the report! This is a fairly new & advanced feature, so sorry for any lack of documentation on the matter. It's also not ideal for all situations, and only tailored as a suggestion for particular types of setups

What I would recommend in your case is to just directly use `set_aligned_timestamps` after performing your own custom method to align the timestamps of the secondary system

I agree our `align_by_interpolation` method (designed for the case you mention of all timestamps to interpolate living within the 'sample space' of the alignment pulses) should try to prevent confusion on this. Out of your suggestions,

To clarify though, you're saying the process is as follows

1) Intan device (main time basis) begins recording (including analog channels)
2) At a later time, NeuroPixels through OpenEphys turns on, starts sending 10 Hz pulse to analog channel on Intan
3) NeuroPixels stops recording before Intan (last pulse sent and received by Intan board)
4) Intan stops recording

If so, then I think our piecewise interpolation method ought to work because the NeuroPixel signal is entirely contained in the time basis of the Intan system, so it sounds like I'm misunderstanding something?



> Throw an error, forcing the user to implement their own alignment logic

This would be my basic preference. Makes the fewest assumptions that can lead to the least number of potential issues and side effects

**Comment by CodyCBakerPhD** [comment]
Oh, I will also add that the `align_by_interpolation` method is primarily designed for a 3-device setup (sorry that's not clearer from [the docs](https://neuroconv.readthedocs.io/en/main/user_guide/temporal_alignment.html#synchronize-based-on-a-synchronization-signal))

1) Primary device receives TTL from secondary device
2) Secondary device receives TTL from tertiary device (but primary device does not see anything from tertiary device)
3) You can interpolate the times from the tertiary into the primary time  basis by leveraging the known secondary alignment

With a 2-device setup as you describe, you would simply need to parse the TTL signal on the Intan analog channel and that gives you the aligned NeuroPixel timestamp in the primary Intan time basis, correct? In which case the interpolation method isn't needed at all; again, let me know if I'm misunderstanding something

**Comment by johnmbarrett** [comment]
No worries, thanks for the quick response! And yes, I'm going to plow ahead with doing things manually with `set_aligned_timestamps`, I just thought this was worth bringing up in case anyone else attempts to use `align_by_interpolation` like I was trying to.

The setup you describe is basically what's happening, yeah, although both recording systems are controlled by Open Ephys GUI and so start near-simultaneously and I have no control over which starts or finishes first (in the recording I'm using for debugging it seems to go NP starts -> Intan starts -> NP ends -> Intan ends). Here's how I'm attempting to align them, in pseudocode:
```
np_alignment_timestamps = # get TTL pulse timestamps as seen by Neuropixels
rhd_alignment_timestamps = # get TTL pulse timetamps as seen by Intan system
np_interface.align_by_interpolation(unaligned_timestamps=np_alignment_timestamps,aligned_timestamps=rhd_alignment_timestamps)
```
The issue arises because `np_alignment_timestamps[0] > np_interface.get_timestamps()[0]` and `np_alignment_timestamps[-1] < np_interface.get_timestamps()[-1]`, by necessity because the Neuropixels system can't record a timestamp before it starts or after it finishes recording. I'm trying to use `align_by_interpolation` because:

1) My first instinct is to try and use existing code as much as possible before rolling my own, and
2) Even though both system are nominally sampling at 30 kHz, the sampling rate isn't guaranteed to be exact, so some interpolation seems like it would be necessary

In practice, my recordings are short enough and the sampling rates close enough that I can probably ignore (2) and just use the two sets of TTL timestamps to figure out the time delta between the two data streams. But I should be able to implement that myself. Thanks again for your help!
