### ISSUE TITLE
[Feature]: Add more keywords for more interfaces

### ISSUE THREAD

**Issue by rly** [catalystneuro/neuroconv#719]
### What would you like to see added to NeuroConv?

NWB GUIDE pulls `keywords` from the `keywords` class variable of the corresponding interface. Some interfaces are missing keywords, which would be helpful for users to search for relevant interfaces.

<img width="1392" alt="image" src="https://github.com/catalystneuro/neuroconv/assets/310197/2dbd0dd9-5198-4b00-b7cf-adb8751c3328">

I am happy to open a PR to add more keywords.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
> I am happy to open a PR to add more keywords.

Please do! Let us know if any questions about how inheritence, etc. works

You can confirm everything in real time by doing dev install of NeuroConv in your `nwb-guide` environment (app should even hot reload)

**Comment by CodyCBakerPhD** [comment]
@rly This has steadily improved over time - do you still want to keep this issue open here?
