### ISSUE TITLE
[Documentation]: ABF conversion in gallery

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#72]
### What would you like changed or added to the documentation and why?

ABF conversion in gallery

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/nwb-conversion-tools/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/nwb-conversion-tools/issues)?

**Comment by CodyCBakerPhD** [comment]
@luiztauffer or @h-mayorquin Looks like this still needs to be done
