### ISSUE TITLE
[Bug]: datetime with local timezone throws OSError when converting file

### ISSUE THREAD

**Issue by EricThomson** [catalystneuro/neuroconv#762]
### What happened?

I'm making a converter for Caiman, and one step is auto-adding a datetime if it isn't specified. I've run into some errors when I use `tz.local()` and have reproduced them when using the `neuroconv` interface. Specifically, if you don't set a time zone, or set it to `tzlocal()` an exception is thrown. 

More in the weeds: if you don't have a timezone, `pynb.file._add_missing_timezone()`  tries to add `tzlocal()`, but downstream functions throw an OSError. I switched to `tz.UTC` to fix it. 

This may be Windows specific 😬 I'm on Windows 10, Python 3.10. Haven't tested on Linux. 

Related to #599 .

### Steps to Reproduce

```python
from datetime import datetime
from dateutil import tz
from neuroconv.datainterfaces import CaimanSegmentationInterface

caiman_file = 'cnmf.hdf5'
nwb_file = 'cnmf_converted.nwb'

interface = CaimanSegmentationInterface(file_path=caiman_data_path, verbose=True)
metadata = interface.get_metadata()
session_start_time = datetime.min.replace(tzinfo=tz.tzlocal())
metadata["NWBFile"].update(session_start_time=session_start_time)
interface.run_conversion(nwbfile_path=nwb_filepath_new, metadata=metadata)
```

### Traceback

```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[30], line 2
      1 # Choose a path for saving the nwb file and run the conversion
----> 2 interface.run_conversion(nwbfile_path=nwb_filepath_new, metadata=metadata)

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\neuroconv\basedatainterface.py:92, in BaseDataInterface.run_conversion(self, nwbfile_path, nwbfile, metadata, overwrite, **conversion_options)
     89 if metadata is None:
     90     metadata = self.get_metadata()
---> 92 with make_or_load_nwbfile(
     93     nwbfile_path=nwbfile_path,
     94     nwbfile=nwbfile,
     95     metadata=metadata,
     96     overwrite=overwrite,
     97     verbose=getattr(self, "verbose", False),
     98 ) as nwbfile_out:
     99     self.add_to_nwbfile(nwbfile_out, metadata=metadata, **conversion_options)

File ~\miniconda3\envs\caiman_nwb_python\lib\contextlib.py:135, in _GeneratorContextManager.__enter__(self)
    133 del self.args, self.kwds, self.func
    134 try:
--> 135     return next(self.gen)
    136 except StopIteration:
    137     raise RuntimeError("generator didn't yield") from None

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\neuroconv\tools\nwb_helpers\_metadata_and_file_helpers.py:184, in make_or_load_nwbfile(nwbfile_path, nwbfile, metadata, overwrite, verbose)
    182 except Exception as e:
    183     success = False
--> 184     raise e
    185 finally:
    186     if nwbfile_path_in:

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\neuroconv\tools\nwb_helpers\_metadata_and_file_helpers.py:180, in make_or_load_nwbfile(nwbfile_path, nwbfile, metadata, overwrite, verbose)
    178         nwbfile = io.read()
    179     elif nwbfile is None:
--> 180         nwbfile = make_nwbfile_from_metadata(metadata=metadata)
    181     yield nwbfile
    182 except Exception as e:

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\neuroconv\tools\nwb_helpers\_metadata_and_file_helpers.py:56, in make_nwbfile_from_metadata(metadata)
     54 schema_path = Path(__file__).resolve().parent.parent.parent / "schemas" / "base_metadata_schema.json"
     55 base_metadata_schema = load_dict_from_file(file_path=schema_path)
---> 56 validate_metadata(metadata=metadata, schema=base_metadata_schema)
     58 nwbfile_kwargs = deepcopy(metadata["NWBFile"])
     59 # convert ISO 8601 string to datetime

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\neuroconv\utils\json_schema.py:330, in validate_metadata(metadata, schema, verbose)
    327 encoder = NWBMetaDataEncoder()
    328 # The encoder produces a serialized object so we deserialized it for comparison
--> 330 serialized_metadata = encoder.encode(metadata)
    331 decoded_metadata = json.loads(serialized_metadata)
    332 validate(instance=decoded_metadata, schema=schema)

File ~\miniconda3\envs\caiman_nwb_python\lib\json\encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)

File ~\miniconda3\envs\caiman_nwb_python\lib\json\encoder.py:257, in JSONEncoder.iterencode(self, o, _one_shot)
    252 else:
    253     _iterencode = _make_iterencode(
    254         markers, self.default, _encoder, self.indent, floatstr,
    255         self.key_separator, self.item_separator, self.sort_keys,
    256         self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\neuroconv\utils\json_schema.py:22, in NWBMetaDataEncoder.default(self, obj)
     19 def default(self, obj):
     20     # Over-write behaviors for datetime object
     21     if isinstance(obj, datetime):
---> 22         return obj.isoformat()
     24     # Transform numpy generic integers and floats to python ints floats
     25     if isinstance(obj, np.generic):

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\dateutil\tz\tz.py:222, in tzlocal.utcoffset(self, dt)
    219 if dt is None and self._hasdst:
    220     return None
--> 222 if self._isdst(dt):
    223     return self._dst_offset
    224 else:

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\dateutil\tz\tz.py:291, in tzlocal._isdst(self, dt, fold_naive)
    288     return False
    290 # Check for ambiguous times:
--> 291 dstval = self._naive_is_dst(dt)
    292 fold = getattr(dt, 'fold', None)
    294 if self.is_ambiguous(dt):

File ~\miniconda3\envs\caiman_nwb_python\lib\site-packages\dateutil\tz\tz.py:260, in tzlocal._naive_is_dst(self, dt)
    258 def _naive_is_dst(self, dt):
    259     timestamp = _datetime_to_timestamp(dt)
--> 260     return time.localtime(timestamp + time.timezone).tm_isdst

OSError: [Errno 22] Invalid argument
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.9

### Package Versions

[environment_for_issue.txt](https://github.com/catalystneuro/neuroconv/files/14421129/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
> and one step is auto-adding a datetime if it isn't specified

This seems dangerous; you mean to say setting the `session_start_time` to something like `datetime.now()`? That is incorrect, which is why we generally require the user to input this information manually. It could be an argument to the function call to write the NWB file in your case. Dates should also be accepted if exact timestamp isn't known (which is fine)


> More in the weeds: if you don't have a timezone, pynb.file._add_missing_timezone() tries to add tzlocal(), but downstream functions throw an OSError. I switched to tz.UTC to fix it.
> 
> This may be Windows specific 😬 I'm on Windows 10, Python 3.10. Haven't tested on Linux.

As for the actual error here, I can reproduce minimally with pure `datetime`/`dateutil`

```python
from datetime import datetime
from dateutil import tz

now = datetime.now()
now_with_local_timezone = now.min.replace(tzinfo=tz.tzlocal())

now_with_local_timezone_as_iso = now_with_local_timezone.isoformat()
> OSError
```

So it seems to me a more fundamental error with `dateutil` to not resolve the `tzlocal()` to something explicit.

We don't recommend relying on `local` timezone anyway since it can easily be incorrect (the behavior of PyNWB to infer it has been a long-time point of internal discussion that may be removed some day; apologies about that), hence why in the [conversion gallery](https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/segmentation/caiman.html) we _always_ recommend setting it explicitly

**Comment by CodyCBakerPhD** [comment]
While we're at it, a kind reminder that if you intend your Caiman output NWB files to  be uploadable to DANDI, they will also need to collect basic subject information as well (again, I'd recommend as required inputs)

These are: `subject_id`, `subject_age` (as ISO duration), `sex` (M/F/O/U), and `species` (latin binomial, e.g., _Mus musculus_)

**Comment by EricThomson** [comment]
Good call with the error, indeed it's the iso conversion. The following throws the same:

`datetime.min.replace(tzinfo=tz.tzlocal()).isoformat()`

For context: I am currently working with a demo dataset where the session start time is unknown, so I'm setting it to something arbitrary so the conversion doesn't throw an error -- in this case the earliest possible `datetime.min` -- I want to use this as an indicator that it was not set, and throwing a warning. I didn't try with a date and no timestamp: I'll give that a shot.

Making things required, versus setting defaults and issuing warnings if they haven't changed them, is something we'll have to discuss internally as a Caiman design question. At the very least, it will be good to get users to think about what minimal information they will wish they had access to in ten months when they open `elsa_reaching_task_day10.nwb`.

**Comment by CodyCBakerPhD** [comment]
> For context: I am currently working with a demo dataset where the session start time is unknown, so I'm setting it to something arbitrary so the conversion doesn't throw an error -- in this case the earliest possible datetime.min -- I want to use this as an indicator that it was not set, and throwing a warning.

I see - for a demo I would still suggest to explicitly type out the placeholder datetime while emphasizing they should enter the correct information for their experiment when using it in practice.

Experience has taught us that more often than not, first time users will in those situations simply copy and paste implicit code-based approaches without understanding what exactly something like a `datetime.min` does



> Making things required, versus setting defaults and issuing warnings if they haven't changed them, is something we'll have to discuss internally as a Caiman design question.

I can tell you from seeing the results of downstream outputs from these types of decisions, I strongly recommend not have a default for something as important as this (or the other subject info for that matter). Users will almost always in those situations rely on the defaults, even when they end up being incorrect, and that just produces NWB files that might go to DANDI with incorrect metadata.

**Comment by EricThomson** [comment]
I appreciate your feedback here! Especially as someone with little experience with NWB I will weight it very heavily!  I'm closing this issue as it was based on me misusing a pattern from `_add_missing_timezone()` (and the warning was there in the leading underscore that I should have been more careful 😄 ).

**Comment by EricThomson** [comment]
Just following up: to add top-level metadata like `Subject` information, it's as simple as adding a new key to the metadata dict from the interface, so something like:

```
metadata = interface.get_metadata()
metadata["Subject"] = {k:v}
```

where `{k:v}` is a stand in for the key/values we want like `subject_id`, etc?

**Comment by CodyCBakerPhD** [comment]
@EricThomson Yep, that should work

We also use a special type of dictionary that allows you to specify keys at any level, so you can optionally do

```python
metadata["Subject"]["subject_id"] = ...
metadata["Subject"]["age"] = "P10W"  # For example; must be ISO 8601
metadata["Subject"]["sex"] = ...
metadata["Subject"]["species"] = ...
```

directly
