### ISSUE TITLE
`IntanRecordingInterface` should not be allowed to write streams other than the amplifier channels

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#790]
From the current discussionin #789  it seems that `IntanRecordingInterface` should only write data with `stream_id=0`: the amplifier channels. Reason being that we write the data as an ElectricalSeries following the ecephys pipeline. This means that if any other stream is choosen the data will be incorrectly written.

The current signature of `IntanRecordingInterface` allows the user to specify the `stream_id` which leads to the problem described above.

https://github.com/catalystneuro/neuroconv/blob/fa6edd532f6bb6ead42ae40aa9029c7c78eead5f/src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py#L77-L95

Should we change this to avoid this scenario?
Pros and cons?

**Comment by CodyCBakerPhD** [comment]
If Intan as a format is that reliable in terms of a particular stream ID mapping onto proper neural channels, then sure we can just restrict the interface to that stream

The argument is usually left open for other formats though out of necessity to select _which_ neural stream in the event of multiple probes, channel groups, bands, etc.

**Comment by h-mayorquin** [comment]
Yeah, stream_0 is fixed at neo to be the amplifier channels. 

It is not clear to me if all the amplifier channels should always be ElectricalSeries but at that point there is nothing we do for now.
