### ISSUE TITLE
[Bug]: Failures in imaging plane name on new ScanImage tests

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#828]
### What happened?

Really not sure what happened to break it on main post merge (since tests had to have been passing at time of merge...) but this block just started erroring on other PRs

### Steps to Reproduce

```python
Caught in CI: https://github.com/catalystneuro/neuroconv/actions/runs/8868996493/job/24349189441

traced to lines: https://github.com/catalystneuro/neuroconv/pull/827/files#diff-8a26fe5d073ef0f17a94da85ec6792dfcfb6f070abd2a8673c8c7e8e3a4899a6L52
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.8

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
@pauladkisson @weiglszonja Could use both of your eyes on this

**Comment by weiglszonja** [comment]
I'm not sure either, tests were passing at the time of merge. I'm not sure how to fix yet, but I think the parameters we want to test defined in `parameterized_class()` are not getting passed, and when comparing the imaging planes we're still comparing to the first one. When running `pytest` locally however, I'm not able to trigger any error.

**Comment by pauladkisson** [comment]
Same, can't get this to replicate locally even from a brand new env and messing around with the pytest version.

**Comment by weiglszonja** [comment]
I'm still looking, but what if the reason we haven't replicated it locally is because in CI we use [pytest-xdist](https://github.com/pytest-dev/pytest-xdist), but I guess that still doesn't really explain why they started to fail suddenly..
