### ISSUE TITLE
Next steps to increase Coverage

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#86]
Recently we accomplished a long-term goal of reaching 90 % coverage on the repo:
https://github.com/catalystneuro/nwb-conversion-tools/issues/277

I am writing here the next steps for the next long term project of increasing this even further, let's say 95 %. The followings is a list of what I believe are the remaining big tickets that can yield big increases in coverage:

## Tools

- [ ] neo (this is the module with less coverage).
- [ ] roiextractors (we have the `get_epochs` functions that we are not using).
- [ ] spikeinterface (mainly the functions concerning adding waveforms).

## Data interfaces
- [ ] Basesorting (has some functionality to add electrode information that we are not testing)
- [ ] Axona (this module has a lot of functions and one data interface that we are not testing).
- [ ] Cell explorer (a lot of functionality that I think belongs properly to the extractor is kept there untested).

## Utils
- [ ] Some of the functionalities in the `dict` module are not tested.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Did you want to keep this open or close and make a new ticket if this becomes an item of interest?

**Comment by h-mayorquin** [comment]
Yeah, let's close this. I don't think it makes sense to have a plan (that is probably outdated) for such a low priority thing.
