### ISSUE TITLE
[Bug]:  Link to your user guide on read the docs is broken

### ISSUE THREAD

**Issue by AngCamp** [catalystneuro/neuroconv#864]
### What happened?

This link https://neuroconv.readthedocs.io/en/main/user_guide/index.rst  from your main page on the read the docs is broken.  https://neuroconv.readthedocs.io/en/main/

### Steps to Reproduce

```python
n/a
```

### Traceback

```python
n/a
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.8

### Package Versions

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Specifically, it seems the top page navigators work fine by leading to respective `.html` pages, but the links from these lines: https://github.com/catalystneuro/neuroconv/blob/main/docs/index.rst?plain=1#L30-L49

route to non-existent `.rst` instead

**Comment by CodyCBakerPhD** [comment]
Thanks for catching this and letting us know @AngCamp, fixed in #865
