### ISSUE TITLE
[Feature]: Option to attach imaging data via external link

### ISSUE THREAD

**Issue by mhturner** [catalystneuro/neuroconv#889]
### What would you like to see added to NeuroConv?

Apologies if there is already a way to do this and I just haven't found it! We would like to use the Bruker Tiff converters (`BrukerTiffSinglePlaneConverter` and `BrukerTiffMultiPlaneConverter`) to `add_to_nwb_file()`, which is working well for attaching the image data directly to the .nwb file. But we'd like to instead just attach an external link, as described in this [pynwb tutorial](https://pynwb.readthedocs.io/en/stable/tutorials/domain/ophys.html#sphx-glr-tutorials-domain-ophys-py). Is this something that neuroconv can do already? Or can you expose that option in the creation of the `TwoPhotonSeries` to the ophys data interfaces? The workaround for now is to write our own conversion in line with the pynwb documentation.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
While this is _technically_ allowed by core PyNWB, it is against the best practices: https://nwbinspector.readthedocs.io/en/dev/best_practices/image_series.html#use-internal-dataset-for-videos-of-neurophysiological-data

NeuroConv serves as more of a bridge for NWB files to reach the DANDI Archive

And the DANDI Archive does not allow externally linked files for this neurodata type - it only allows a handful of video types for behavioral data

**Comment by mhturner** [comment]
Gotcha. That makes sense. Thank you for the response!

**Comment by CodyCBakerPhD** [comment]
Absolutely - just let us know if/when you have any more questions 😊
