### ISSUE TITLE
[Bug]: run_conversion(overwrite=True) does not overwrite an improperly formatted NWB file

### ISSUE THREAD

**Issue by tabedzki** [catalystneuro/neuroconv#910]
### What happened?

During debugging of `add_to_nwbfile` in my code, I would often crash or quit the python process part of the way through writing the NWB file, leaving it improperly formatted. 

So running the following code twice (once that you stop part way through and once after that) will yield the errors below. Is there any way to handle this error? 

### Steps to Reproduce

```python
interface.run_conversion(
    # nwbfile_path=nwbfile_path,
    nwbfile_path="./fdf19.nwb",
    metadata=metadata,
    overwrite=True)
```

### Traceback

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], line 22
     16 print(metadata)
     19 # interface.create_nwbfile(metadata=metadata)
     20 # interface.create_nwbfile(metadata=metadata)
---> 22 interface.run_conversion(
     23     # nwbfile_path=nwbfile_path,
     24     nwbfile_path="./fdf19.nwb",
     25     metadata=metadata,
     26     overwrite=True
     27     )

File ~/code/neuroconv/src/neuroconv/basedatainterface.py:167, in BaseDataInterface.run_conversion(self, nwbfile_path, nwbfile, metadata, overwrite, backend, backend_configuration, **conversion_options)
    164 if metadata is None:
    165     metadata = self.get_metadata()
--> 167 with make_or_load_nwbfile(
    168     nwbfile_path=nwbfile_path,
    169     nwbfile=nwbfile,
    170     metadata=metadata,
    171     overwrite=overwrite,
    172     backend=backend,
    173     verbose=getattr(self, "verbose", False),
    174 ) as nwbfile_out:
    175     if no_nwbfile_provided:
    176         self.add_to_nwbfile(nwbfile=nwbfile_out, metadata=metadata, **conversion_options)

File /opt/anaconda3/envs/neuroconv_3.12/lib/python3.12/contextlib.py:137, in _GeneratorContextManager.__enter__(self)
    135 del self.args, self.kwds, self.func
    136 try:
--> 137     return next(self.gen)
    138 except StopIteration:
    139     raise RuntimeError("generator didn't yield") from None

File ~/code/neuroconv/src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py:209, in make_or_load_nwbfile(nwbfile_path, nwbfile, metadata, overwrite, backend, verbose)
    203 else:
    204     load_kwargs.update(mode="w")
    206 backends_that_can_read = [
    207     backend_name
    208     for backend_name, backend_io_class in BACKEND_NWB_IO.items()
--> 209     if backend_io_class.can_read(path=str(nwbfile_path_in))
    210 ]
    211 # Future-proofing: raise an error if more than one backend can read the file
    212 assert (
    213     len(backends_that_can_read) <= 1
    214 ), "More than one backend is capable of reading the file! Please raise an issue describing your file."

File /opt/anaconda3/envs/neuroconv_3.12/lib/python3.12/site-packages/pynwb/__init__.py:272, in NWBHDF5IO.can_read(path)
    270 try:
    271     with h5py.File(path, "r") as file:   # path is HDF5 file
--> 272         return get_nwbfile_version(file)[1][0] >= 2    # Major version of NWB >= 2
    273 except IOError:
    274     return False

TypeError: 'NoneType' object is not subscriptable
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.12

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
A shame PyNWB/HDMF doesn't have great annotation typing, so hard to tell from signature of https://github.com/NeurodataWithoutBorders/pynwb/blob/90e60484415d38d3d566dc9fea63b6d99ffdbe43/src/pynwb/__init__.py#L183 that it can return `None`

Will get a short circuit exit condition in to fix this, thanks for catching!

**Comment by h-mayorquin** [comment]
Thanks for reporting this @tabedzki. I have encountred this error myself. The fix in https://github.com/catalystneuro/neuroconv/pull/911 works but shouldn't the context manager erase the file if something fails as well? I wonder if this is possible or desirable.

**Comment by h-mayorquin** [comment]
Also, should we fill a bug in pynwb for this? The version returns None but they want to subscript it also.

**Comment by CodyCBakerPhD** [comment]
A ticket on PyNWB wouldn't hurt. The logic of `.can_read` should not error if the file is corrupt (unable to get version), but should simply return `False`

**Comment by CodyCBakerPhD** [comment]
> but shouldn't the context manager erase the file if something fails as well?

Only if `overwrite=True`, otherwise you could accidentally erase 'good' files that were simply pointed to by mistake. Same reason `overwrite=False` by default; automatically deleting files without asking for user confirmation could have dire consequences

**Comment by h-mayorquin** [comment]
I mean when the file was created using neuroconv.
Two steps in my case:
1)  I was writing files using neuroconv, then something would fail.
2) I will try to re-run the script and this error would appear.

If I understand you the erasing should not happen in two and I agree. But I am saying, why is the file is not erase in 1?

I thought that our context was doing that:

https://github.com/catalystneuro/neuroconv/blob/6808a3cd3ed053639df64c284e95eb34f66e2f41/src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py#L226-L247

Maybe I did not understand you but I wanted to be more clear. Does this make sense?

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Are you setting `overwrite=True` in 1 and 2?

Also while the automatic cleanup behavior is desired, on various platforms `unlink` is not necessarily guaranteed to be successful in removing the files (usually due to some latent file handles still being open), so in leiu of that we can also check in step 2 if we even need to interact with an existing file at all or just always attempt to overwrite it if that is the mode the user wants to write with

**Comment by h-mayorquin** [comment]
Yes, I am using it on both.

Writing a small discussion PR on #912 just to make this explicit. 
We already have deletion of files in uncesful use of read or create with metadata but we don't have removal with attemping to write which is where I think the error arrises.

I agree with the concerns of how windows handles deletions (it tries to do it automtically instead of queing it like linux). Maybe we should remove both unlik? Anyway, check the PR.
