### ISSUE TITLE
[Feature]: Correct scaling is lost from Blackrock recordings by excluding gain_to_uV and offset_to_uV from recording properties

### ISSUE THREAD

**Issue by daltondm** [catalystneuro/neuroconv#916]
### What would you like to see added to NeuroConv?

I am working with Blackrock recording files (.ns6 and .nev), for which the .ns6 files contain both electrophysiology channels and analog input channels. The metadata in the .ns6 file indicates that ephys channels are saved with gain_to_uV = 0.25, while the analog channels have gain_to_uV ~= 125. NWB files I created with previous versions of Neuroconv store this information so that I am able to reconstruct the signal accurately, but the latest version excludes both offset_to_uV and gain_to_uV from the recorder properties - this makes accurate reconstruction impossible from the stored channel properties. 

The exclusion occurs in line 251 of [src/neuroconv/tools/spikeinterface/spikeinterface.py](https://github.com/catalystneuro/neuroconv/blob/e2161f20478272250f4ef9f465944e65322f6a1d/src/neuroconv/tools/spikeinterface/spikeinterface.py#L251)

Is there a principled reason for excluding these properties, and is there a workaround for storing this information? Perhaps the exclusion could be made optional?  

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
The same information should be available as the `conversion` and `offset` attributes on the resulting `ElectricalSeries` object (albeit +/- scaling factor from $\mu V$ to $V$)

**Comment by daltondm** [comment]
Thank you. You're right, the files have that information in the `channel_conversion` attibute. My apologies, I should have thought to check there. Thank you for your help!
