### ISSUE TITLE
[Bug]: local timezone added to EDF session start time

### ISSUE THREAD

**Issue by rohanshah** [catalystneuro/neuroconv#938]
### What happened?

This is not a bug per-se, more unexpected functionality.

When using the EDF converter, `pynwb` will set the timezone on the session start time to the computer's local time.

Given that the EDF file format itself doesn't contain timezone information, this added information makes running the EDF converter somewhat inconsistent i.e. running the converter locally vs in a deployed environment can produce different start times in the output NWB file.

For clarity, the reasoning behind why `pynwb` sets the session start time timezone to the computer's local time is discussed in this issue: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/50 and implemented here: https://github.com/NeurodataWithoutBorders/pynwb/pull/641

### Proposal
Given that EDF itself doesn't specify a timezone for its start date/time

Given that the user performing the conversion to NWB might be in a different timezone than where the EDF file was produced 

When reading the raw metadata from EDF file set the `startdate` timezone to `UTC`, before NWB file creation. Here: https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/datainterfaces/ecephys/edf/edfdatainterface.py#L49 

This would be a best effort to make the session start time in the NWB file as timezone-less (and thus as close to the original EDF file) as possible.

### Steps to Reproduce

```python
interface = EDFRecordingInterface(file_path=edf_file_path)
metadata = interface.get_metadata()
interface.run_conversion(nwbfile_path=nwb_file_path, metadata = metadata)
```

### Traceback

```python
/opt/venv/lib/python3.12/site-packages/pynwb/file.py:472: UserWarning: Date is missing timezone information. Updating to local timezone.
  args_to_set['session_start_time'] = _add_missing_timezone(session_start_time)
```

### Operating System

macOS

### Python Executable

Python

### Python Version

3.12

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Thanks for the detailed thoughts on this matter

These types of issues and choices are exactly why we emphasize the explicit setting of timezone throughout our conversion gallery: https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/recording/edf.html

That is the best we can do on NeuroConv and the NWB GUIDE (which has a graphical selector of available timezones), as this is more of a [NWB schema](https://github.com/NeurodataWithoutBorders/nwb-schema) issue - could you add your thoughts over there?

Setting UTC automatically is just as arbitrary (and still false) of a decision as setting the local computer timezone. Neither is ideal, and the requirement of a timezone in the `session_start_time` is a long and hotly debated issue in the NWB schema. There were recent efforts to make it not required at all (and thus not set to potentially incorrect values) on the NWB side, but they broke DANDI publication requirements (leading up to https://github.com/pydantic/pydantic/issues/9518) so it was all reverted in the end

**Comment by rohanshah** [comment]
@CodyCBakerPhD thanks for taking a look and your insight! 

The recommendation to have the end user set the timezone explicitly makes total sense, and is definitely the approach I'll take on my end.

Also happy to add my thoughts over on the NWB schema if they're not too redundant to what's already been discussed.

And that's interesting to know that there was effort to remove the need for timezone altogether!

I had initially thought the EDF conversion a good spot to make the proposed change because EDF itself under specifies its start time, such that the information might be lost (in communication) between recording and the actual usage of the data

and while

>  Setting UTC automatically is just as arbitrary (and still false) of a decision as setting the local computer timezone. Neither is ideal

is totally true, UTC+0 would at least indicate no offset should be applied to the given time, and would maintain consistency across runtime environments e.g. local development vs. a production pipeline.

Again, totally happy to add those last thoughts over on the NWB schema page if they positively contribute to the conversation.

Just wanted to leave my thoughts here for posterity in case anyone comes across a similar issue.

Feel free to close out the issue if you think it best to leave the EDF converter as is!

Thanks again!

**Comment by rohanshah** [comment]
I should also add for context, the reason I originally ran into this issue and proposed the given change was that I had utilized the neuroconv Docker runtime, instead of using the Python library, and there was no way (as far as I could tell) to intercept the read metadata and apply that explicitly timezone setting that the documentation recommends. Perhaps that's a separate issue worth looking into?

**Comment by CodyCBakerPhD** [comment]
> Also happy to add my thoughts over on the NWB schema if they're not too redundant to what's already been discussed.

The thoughts have been shared before, yes, but it's more about 'casting your vote' or 'poking the sleeping dragon'

If enough people rally to push the system in a given direction, it makes it a higher priority, more momentum, higher chance of success, etc...

So yes, please share your thoughts with the rest of the community at the highest level
