### ISSUE TITLE
[Bug]: Show example pip install instructions with quotes for mac users

### ISSUE THREAD

**Issue by rly** [catalystneuro/neuroconv#947]
### What happened?

I just worked with a user who had previously run `pip install neuroconv[openephys]` on a Mac, got the error `zsh: no matches found: neuroconv[openephys]`, and gave up, thinking it just doesn't work on their system or neuroconv is broken.

I believe `pip install "neuroconv[openephys]"` with double quotes should work fine on all common shells. MacOS uses zsh (as of Catalina, released in 2019) which requires quotes around square brackets. Bash works fine with no quotes or quotes. I think Windows Powershell requires quotes. Single quotes do not work on Windows cmd. So I suggest using double quotes in all `pip install` instructions.

related: https://github.com/mu-editor/mu/issues/852 and https://discuss.python.org/t/pep-621-how-to-specify-dependencies/4599/61

### Steps to Reproduce

```python
pip install neuroconv[openephys] on a Mac
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.11

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
This has always been included as a note on step 1 of the user guide: https://neuroconv.readthedocs.io/en/main/user_guide/datainterfaces.html#installation

Could consider just adding quotes to all galleries

**Comment by bendichter** [comment]
Yes, I think adding quotes to all the gallery pages is a good idea

**Comment by rly** [comment]
Thanks for the quick fix!
