### ISSUE TITLE
Append mode metadata validation requires `session_start_time` for an existing NWB file.

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#954]
When thinking about https://github.com/catalystneuro/neuroconv/pull/949 I realized the following.

Right now `run_conversion` supports append mode when we pass an `nwbfile_path` that points to a file that already exists. However, we always do metadata validation:

https://github.com/catalystneuro/neuroconv/blob/0866c30ff5378bfe66a2221662dfb8cb97ecbe33/src/neuroconv/nwbconverter.py#L220-L221

The problem with this is that `session_start_time` is demanded by `validate_metadata` even if the file was already created but I don't think this makes sense. Those attributes are already there.
 
Minimal example:
```python
from neuroconv.tools.testing.mock_interfaces import MockRecordingInterface
from neuroconv import ConverterPipe
from pynwb.testing.mock.file import mock_NWBFile
from pynwb import NWBHDF5IO
import tempfile

nwbfile = mock_NWBFile()


with tempfile.TemporaryDirectory() as tmpdir:
    
    nwbfile_path = Path(tmpdir) / 'test.nwb'
    with NWBHDF5IO(nwbfile_path, 'w') as io:
        io.write(nwbfile)

    recording_interface = MockRecordingInterface()
    # Dynamically assign the parent class's get_metadata method to the instance
    # This is because the MockRecordingInterface has metadata with session_start_time and I want to avoid it to showcase the problem
    recording_interface.get_metadata = MockRecordingInterface.__bases__[0].get_metadata.__get__(recording_interface, MockRecordingInterface)    
    converter_pipe = ConverterPipe(data_interfaces=[recording_interface])
    
    converter_pipe.run_conversion(nwbfile_path=nwbfile_path)
```

I don't know how to fix this. I guess that the "complete" solution is to check for the unique attributes already present on the nwbfile and don't validate those as necessary. We can do this for the things that live on metadata["NWBFile"]

Other options:
* Don't validate metadata in append mode (seems wrong)
* We can have a list of terms in metadata["NWBFile"] that are necessary for creation and unique and skip those in append mode.
* We can just skip the validation of `session_start_time` in append mode which in practice is the one that will cause problems I think.

What do you think @CodyCBakerPhD @bendichter, maybe we can discuss this on the next team meeting unless the solution is obvious to you guys.

**Comment by CodyCBakerPhD** [comment]
This type of thing was pretty common to see throughout developing GUIDE

There's lots of places where metadata requirements are very 'conditional' (if one thing elsewhere in the metadata or even outside as in this case takes a particular value, then the state of other parts of the schema change)

That's easy to fix in GUIDE since every page dynamically alters its metadata on interaction

Doing that programmatically in NeuroConv is very hard, however, since the sequence of interactions is not as constrained

Anyway, a minimal fix I can recommend outright for this specific issue is to note that this would mean that `get_metadata_schema` is dependent on the `mode` value determined via (i) `nwbfile_path`, (ii) `overwrite`, (iii) logic about whether or not the file exists already, such that if `mode="a"` then `"session_start_time"` can be removed from the `["NWBFile"]["requirements"]` before validating

That said, it is only one field, and it should be present for the majority is circumstances, so whether or not this kind of complicated 'fix' is worth it for such a minor detail (as nonsensical as the requirement is in that case) is the real question

**Comment by h-mayorquin** [comment]
I mean, if we want to support append mode then either we:
1. Put the burden on the users of add an artificial `session_start_time` in their metadata so they can bypass the nonsensical requirement.
2. We do the work ourselves to avoid the requirement.

I am of the philosophy that the burden should always be on the programmer and not in the user so 2 is the way to go for me. 

From memory I think  most interfaces do not have `session_start_time` though. Maybe I am wrong about this.

**Comment by CodyCBakerPhD** [comment]
If append mode is detected, and `metadata` is passed without `session_start_time`, you could also inject a small pre-step to automatically fetch the current `session_start_time` inside the file and it include it in the `metadata` dictionary without having to mess with the schema at all

**Comment by CodyCBakerPhD** [comment]
Either way I think you should take a stab at this to get more experience working with the metadata and validation routines

**Comment by h-mayorquin** [comment]
> If append mode is detected, and `metadata` is passed without `session_start_time`, you could also inject a small pre-step to automatically fetch the current `session_start_time` inside the file and include it in the `metadata` dictionary without having to mess with the schema at all

Thank you @CodyCBakerPhD . That seems like an easy solution that will solve 99 % of the problematic cases without too much work.

I will wait for @bendichter but assign myself this for the reasons you mentioned just above.

**Comment by bendichter** [comment]
You should also alter the validator to ignore the `required` constraint:

```python
import jsonschema
from jsonschema import Draft7Validator

# Define your schema
schema = {
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "age": {"type": "integer"},
        "email": {"type": "string", "format": "email"}
    },
    "required": ["name", "age", "email"]
}

# Create a custom validator that ignores required fields
all_validators = Draft7Validator.VALIDATORS.copy()
all_validators.pop("required", None)

CustomValidator = jsonschema.validators.create(
    meta_schema=Draft7Validator.META_SCHEMA,
    validators=all_validators
)

# Use the custom validator
data = {
    "name": "John Doe",
    # "age" and "email" are missing, but won't cause validation errors
}

validator = CustomValidator(schema)
errors = list(validator.iter_errors(data))

print(f"Number of validation errors: {len(errors)}")
for error in errors:
    print(error.message)
```

**Comment by bendichter** [comment]
Or you could remove session_start_time as a require field from the metadata schema

**Comment by h-mayorquin** [comment]
Closing this as solved by https://github.com/catalystneuro/neuroconv/pull/949. At the end, the solution implemented was to remove the required arguments from the NWBFile part of the metadata as Ben proposed above.

As I am writing this I am thiking that in fact that part of the metadata (e.g. metadata["NWBFile"] only make sense to validate when creating an nwbfile (calling create_nwbfile) and does not really make sense to validate when calling `add_to_nwb` as the later takes an existing nwbfile as an argument.

But probably better for another issue if a problem with that ever arises.
