### ISSUE TITLE
[Bug]: Dimension mismatch for SpikeGLX data with more than one electrical recording

### ISSUE THREAD

**Issue by tabedzki** [catalystneuro/neuroconv#958]
### What happened?

Approaches taken:

- Successfully enter the conversion routine for both imec folders individually if I use two SpikeGLXRecordingInterface s within the definition of my NWBConverter (one for the LF and one for the recording itself)
  - I had no problems doing an individual LFP conversion, an individual recording conversion and no problems for a combined LF/Recording conversion
- However, if I point to the root folder ya008_20240525_g0 for use with the SpikeGLXConverterPipe , I get a shape mismatch warning on line 90 in [ecephys.py](https://github.com/NeurodataWithoutBorders/pynwb/blob/20c5d75a6ce0b2deb729b81803c9c6440cff029c/src/pynwb/ecephys.py#L90) where the len(args_to_set['electrodes'].data) = 672 and data_shape = (117364459, 384).
  - We have two probes, each with 384 channels/electrodes
  - However, they are being combined in a way that causes a shape/dimensionality mismatch.

### Steps to Reproduce

```python
1. Use the SpikeGLXConverterPipe as an interface for NWBConverter in lieu of SpikeGLXRecordingInterface
```

### Traceback

```python
data_shape=(117364459, 384)
len(args_to_set['electrodes'].data)=672
/opt/anaconda3/envs/neuroconv_3.12/lib/python3.12/site-packages/pynwb/ecephys.py:90: UserWarning: ElectricalSeries 'ElectricalSeriesAPIMEC0': The second dimension of data does not match the length of electrodes. Your data may be transposed.
  warnings.warn("%s '%s': The second dimension of data does not match the length of electrodes. "
/opt/anaconda3/envs/neuroconv_3.12/lib/python3.12/site-packages/pynwb/ecephys.py:90: UserWarning: ElectricalSeries 'ElectricalSeriesLFIMEC0': The second dimension of data does not match the length of electrodes. Your data may be transposed.
  warnings.warn("%s '%s': The second dimension of data does not match the length of electrodes. "
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.12

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
Thanks for reporting this. My initial hunch is that it might be related to how the metadata is arranged that is causing some mismatch in the creation of electrodes here:

https://github.com/catalystneuro/neuroconv/blob/5986a72a2d3fa5a0cfc20b4ad5fa6d3954d096a9/src/neuroconv/tools/spikeinterface/spikeinterface.py#L668-L678

Is the data too large? Could you share it with us so I can debug this?

**Comment by tabedzki** [comment]
Hi Herberto, 
The total data size is 182G total. I'd be happy to share the metadata with you, but I'd have to check with the PIs and IT how (and if) I would be able to share the raw binaries.

I remember that Shan had access to Princeton's servers. Does CatalystNeuro still have access to the PNI servers?

**Comment by h-mayorquin** [comment]
I am not aware if we do, maybe @CodyCBakerPhD knows. What type of configuration of spikeinterface is? Maybe I can reproduce by loading two of our test examples.

**Comment by h-mayorquin** [comment]
I think this should be solved with https://github.com/catalystneuro/neuroconv/pull/977.

**Comment by tabedzki** [comment]
@h-mayorquin  Thanks for checking in. I'll run the conversion and get back to you.

**Comment by tabedzki** [comment]
@h-mayorquin  this solves my issues. I no longer see the UserWarning about dimensional mismatch. 
This can be closed out for me, unless you want to keep to keep it open as part of tracking other issues.
