### ISSUE TITLE
Use typing.Literals

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#96]
### What would you like to see added to NeuroConv?

There's a bunch of places throughout NeuroConv (and other packages in the ecosystem, too...) where [typing.Literal](https://docs.python.org/3.8/library/typing.html#typing.Literal) would make more sense than what the current annotation types are.

However, this annotation type is not supported in Python 3.7 (only 3.8+), so this will have to wait until we drop support for Python 3.7 (likely when security updates stop going out for it in summer 2023).

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by bendichter** [comment]
Good idea!

**Comment by CodyCBakerPhD** [comment]
I've at least gotten in the habit of putting this in currently in a commented state. I.e.,

```python
def SomeFunc(
    some_arg: str,  # Literal["option_1", "option_2"]
...
```

I can go through and add these everywhere needed for now in order to call this issue 'done' to remove it from backlog, then in the future replace actual annotation with the comment.
