### ISSUE TITLE
[DevOps]: Separate data caching from other workflows

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#993]
### What would you like to see added to NeuroConv?

Both doctests and the later parts of our main test suite here on NeuroConv rely on the example data cache

The GUIDE also has multiple parts that each rely on such a mechanism, but we did something there that made it nicer - we made the caching it's own job and made the downstream runs dependent on its success: https://github.com/NeurodataWithoutBorders/nwb-guide/blob/main/.github/workflows/example_data_cache.yml

I suggest following that strategy @pauladkisson @h-mayorquin as it would alleviate the failures that started to be seen today, such as in https://github.com/catalystneuro/neuroconv/pull/992

It also simplifies things by keeping the actions more modular rather than having cache handling steps integrated within the main CI tests

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
This is a good idea. There are new developments in cross oss caching that might simplify this even further:

https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache

**Comment by h-mayorquin** [comment]
@pauladkisson do you want to optimize this further or are you pleased with the improvements on #1095?

**Comment by pauladkisson** [comment]
Yeah, I think #1095 should close this issue.
